/* ==========================================================================
   seed-words.js — a starter vocabulary list, added once to a new word bank
   (see Storage.seedWordsOnce in storage.js). Definitions/synonyms/antonyms
   written by hand rather than pulled from the dictionary APIs.
   Concrete/technical nouns without a real antonym (lavatory, silo, writ,
   cummerbund, ulcer, etc.) are left with an empty antonyms list rather than
   a forced/inaccurate pairing.

   Note: "Bouyant" (as given) is a common misspelling — stored here with
   its correct spelling, "Buoyant".
   ========================================================================== */

const SEED_WORDS = [
  {
    word: 'Defilement',
    partOfSpeech: 'noun',
    meaning: 'The act of making something impure, dirty, or corrupt; desecration of something pure or sacred.',
    synonyms: ['pollution', 'corruption', 'desecration', 'contamination'],
    antonyms: ['purification', 'cleansing'],
  },
  {
    word: 'Vilification',
    partOfSpeech: 'noun',
    meaning: 'Abusive or slanderous talk about someone; the act of speaking ill of a person.',
    synonyms: ['defamation', 'slander', 'denigration', 'disparagement'],
    antonyms: ['praise', 'commendation'],
  },
  {
    word: 'Ostracism',
    partOfSpeech: 'noun',
    meaning: 'Exclusion from a group or society; the act of shunning or banishing someone.',
    synonyms: ['exclusion', 'banishment', 'exile', 'shunning'],
    antonyms: ['inclusion', 'acceptance'],
  },
  {
    word: 'Trough',
    partOfSpeech: 'noun',
    meaning: 'A long, narrow, open container that holds food or water for animals; also the low point of a cycle or wave.',
    synonyms: ['manger', 'basin'],
    antonyms: ['peak', 'crest'],
  },
  {
    word: 'Lavatory',
    partOfSpeech: 'noun',
    meaning: 'A room or fixture equipped for washing and toileting; a bathroom.',
    synonyms: ['bathroom', 'restroom', 'washroom', 'latrine'],
    antonyms: [],
  },
  {
    word: 'Barracks',
    partOfSpeech: 'noun',
    meaning: 'A building or group of buildings used to house soldiers.',
    synonyms: ['quarters', 'garrison', 'encampment'],
    antonyms: [],
  },
  {
    word: 'Silo',
    partOfSpeech: 'noun',
    meaning: 'A tall tower or pit used to store grain or other bulk material.',
    synonyms: ['granary', 'storehouse', 'bin'],
    antonyms: [],
  },
  {
    word: 'Arsenal',
    partOfSpeech: 'noun',
    meaning: 'A collection or supply of weapons; a place where weapons are made or stored.',
    synonyms: ['armory', 'cache', 'stockpile'],
    antonyms: [],
  },
  {
    word: 'Arboretum',
    partOfSpeech: 'noun',
    meaning: 'A place, often a botanical garden, where trees and shrubs are grown for study and public display.',
    synonyms: ['botanical garden', 'tree garden'],
    antonyms: [],
  },
  {
    word: 'Cadet',
    partOfSpeech: 'noun',
    meaning: 'A student training to become an officer in the military or police.',
    synonyms: ['trainee', 'recruit', 'apprentice'],
    antonyms: [],
  },
  {
    word: 'Leery',
    partOfSpeech: 'adjective',
    meaning: 'Wary or suspicious; cautious about someone or something.',
    synonyms: ['wary', 'suspicious', 'distrustful', 'skeptical'],
    antonyms: ['trusting', 'confident', 'unsuspecting'],
  },
  {
    word: 'Embryonic',
    partOfSpeech: 'adjective',
    meaning: 'In an early, undeveloped stage; not yet fully formed.',
    synonyms: ['incipient', 'rudimentary', 'undeveloped', 'nascent'],
    antonyms: ['mature', 'developed', 'full-grown'],
  },
  {
    word: 'Ephemeral',
    partOfSpeech: 'adjective',
    meaning: 'Lasting for a very short time; fleeting.',
    synonyms: ['fleeting', 'transient', 'momentary', 'short-lived'],
    antonyms: ['permanent', 'everlasting', 'enduring'],
  },
  {
    word: 'Exalt',
    partOfSpeech: 'verb',
    meaning: 'To raise in rank, honor, or power; to praise highly.',
    synonyms: ['glorify', 'extol', 'elevate', 'revere'],
    antonyms: ['degrade', 'demean', 'disparage'],
  },
  {
    word: 'Fickle',
    partOfSpeech: 'adjective',
    meaning: 'Changing frequently, especially in loyalties or affections; inconstant.',
    synonyms: ['capricious', 'inconstant', 'volatile', 'changeable'],
    antonyms: ['steadfast', 'constant', 'loyal'],
  },
  {
    word: 'Flotsam',
    partOfSpeech: 'noun',
    meaning: 'Wreckage or debris found floating on the sea; discarded or scattered odds and ends.',
    synonyms: ['debris', 'wreckage', 'jetsam'],
    antonyms: [],
  },
  {
    word: 'Forge',
    partOfSpeech: 'verb',
    meaning: 'To form or shape something, especially through effort; or to make a fraudulent copy of something.',
    synonyms: ['fabricate', 'fashion', 'shape'],
    antonyms: [],
  },
  {
    word: 'Germane',
    partOfSpeech: 'adjective',
    meaning: 'Relevant to a subject under consideration; pertinent.',
    synonyms: ['relevant', 'pertinent', 'applicable', 'apt'],
    antonyms: ['irrelevant', 'unrelated', 'extraneous'],
  },
  {
    word: 'Glean',
    partOfSpeech: 'verb',
    meaning: 'To gather information or material bit by bit, often from various sources.',
    synonyms: ['gather', 'extract', 'collect', 'harvest'],
    antonyms: [],
  },
  {
    word: 'Inane',
    partOfSpeech: 'adjective',
    meaning: 'Silly, senseless, or lacking substance; foolish.',
    synonyms: ['senseless', 'foolish', 'vapid', 'absurd'],
    antonyms: ['sensible', 'profound', 'meaningful'],
  },
  {
    word: 'Ingress',
    partOfSpeech: 'noun',
    meaning: 'The act of entering; a means or place of entry.',
    synonyms: ['entry', 'entrance', 'access', 'admission'],
    antonyms: ['egress', 'exit', 'departure'],
  },
  {
    word: 'Innocuous',
    partOfSpeech: 'adjective',
    meaning: 'Not harmful or offensive; harmless.',
    synonyms: ['harmless', 'benign', 'inoffensive', 'safe'],
    antonyms: ['harmful', 'dangerous', 'noxious'],
  },
  {
    word: 'Laudatory',
    partOfSpeech: 'adjective',
    meaning: 'Expressing praise; commendatory.',
    synonyms: ['complimentary', 'commendatory', 'approving', 'admiring'],
    antonyms: ['critical', 'disparaging', 'derogatory'],
  },
  {
    word: 'Lucrative',
    partOfSpeech: 'adjective',
    meaning: 'Producing a great deal of profit; profitable.',
    synonyms: ['profitable', 'remunerative', 'gainful', 'moneymaking'],
    antonyms: ['unprofitable', 'worthless'],
  },
  {
    word: 'Mirage',
    partOfSpeech: 'noun',
    meaning: 'An optical illusion caused by atmospheric conditions; something illusory that appears real.',
    synonyms: ['illusion', 'hallucination', 'phantom', 'delusion'],
    antonyms: ['reality'],
  },
  {
    word: 'Null',
    partOfSpeech: 'adjective',
    meaning: 'Having no value, effect, or significance; nonexistent or invalid.',
    synonyms: ['void', 'invalid', 'nonexistent', 'empty'],
    antonyms: ['valid', 'significant', 'existent'],
  },
  {
    word: 'Overt',
    partOfSpeech: 'adjective',
    meaning: 'Done or shown openly; not hidden or secret.',
    synonyms: ['open', 'obvious', 'manifest', 'apparent'],
    antonyms: ['covert', 'hidden', 'secret', 'concealed'],
  },
  {
    word: 'Invaluable',
    partOfSpeech: 'adjective',
    meaning: 'Extremely useful or valuable; indispensable.',
    synonyms: ['priceless', 'indispensable', 'precious', 'essential'],
    antonyms: ['worthless', 'useless', 'dispensable'],
  },
  {
    word: 'Rife',
    partOfSpeech: 'adjective',
    meaning: 'Of common occurrence; widespread, especially something undesirable.',
    synonyms: ['widespread', 'abundant', 'prevalent', 'common'],
    antonyms: ['rare', 'scarce', 'uncommon'],
  },
  {
    word: 'Shroud',
    partOfSpeech: 'verb',
    meaning: 'To cover, conceal, or envelop something, hiding it from view.',
    synonyms: ['cover', 'veil', 'cloak', 'conceal'],
    antonyms: ['reveal', 'expose', 'uncover'],
  },
  {
    word: 'Tacit',
    partOfSpeech: 'adjective',
    meaning: 'Understood or implied without being stated directly.',
    synonyms: ['implied', 'unspoken', 'implicit', 'understood'],
    antonyms: ['explicit', 'stated', 'expressed'],
  },
  {
    word: 'Writ',
    partOfSpeech: 'noun',
    meaning: 'A formal written order issued by a court or other legal authority.',
    synonyms: ['decree', 'mandate', 'summons', 'order'],
    antonyms: [],
  },
  {
    word: 'Cummerbund',
    partOfSpeech: 'noun',
    meaning: 'A broad, pleated waist sash, often worn with men’s formal wear.',
    synonyms: ['sash', 'waistband'],
    antonyms: [],
  },
  {
    word: 'Ulcer',
    partOfSpeech: 'noun',
    meaning: 'An open sore on an internal or external body surface, caused by a break in tissue that fails to heal.',
    synonyms: ['sore', 'lesion', 'abscess'],
    antonyms: [],
  },
  {
    word: 'Buoyant',
    partOfSpeech: 'adjective',
    meaning: 'Cheerful and optimistic, quick to recover from setbacks; also, able to float.',
    synonyms: ['cheerful', 'optimistic', 'resilient', 'upbeat'],
    antonyms: ['despondent', 'gloomy', 'dejected'],
  },
  {
    word: 'Scrutinize',
    partOfSpeech: 'verb',
    meaning: 'To examine or inspect something closely and thoroughly.',
    synonyms: ['examine', 'inspect', 'analyze', 'study'],
    antonyms: ['ignore', 'overlook', 'skim'],
  },
  {
    word: 'Agony',
    partOfSpeech: 'noun',
    meaning: 'Extreme physical or mental suffering.',
    synonyms: ['anguish', 'torment', 'suffering', 'distress'],
    antonyms: ['comfort', 'relief', 'bliss'],
  },
  {
    word: 'Sanguine',
    partOfSpeech: 'adjective',
    meaning: 'Optimistic or positive, especially in a difficult situation.',
    synonyms: ['optimistic', 'hopeful', 'positive', 'confident'],
    antonyms: ['pessimistic', 'gloomy', 'despondent'],
  },
  {
    word: 'Inebriated',
    partOfSpeech: 'adjective',
    meaning: 'Drunk; intoxicated with alcohol.',
    synonyms: ['intoxicated', 'drunk', 'tipsy'],
    antonyms: ['sober', 'clearheaded'],
  },
  {
    word: 'Nihilistic',
    partOfSpeech: 'adjective',
    meaning: 'Believing that life is meaningless and traditional values are unfounded.',
    synonyms: ['cynical', 'skeptical', 'pessimistic'],
    antonyms: ['idealistic', 'optimistic'],
  },
  {
    word: 'Intrepid',
    partOfSpeech: 'adjective',
    meaning: 'Fearless and adventurous, especially in the face of danger.',
    synonyms: ['fearless', 'brave', 'bold', 'courageous'],
    antonyms: ['timid', 'cowardly', 'fearful'],
  },
  {
    word: 'Parsimonious',
    partOfSpeech: 'adjective',
    meaning: 'Extremely unwilling to spend money or use resources; stingy.',
    synonyms: ['stingy', 'miserly', 'frugal', 'tightfisted'],
    antonyms: ['generous', 'extravagant', 'lavish'],
  },
  {
    word: 'Thrifty',
    partOfSpeech: 'adjective',
    meaning: 'Careful and prudent with money; economical.',
    synonyms: ['frugal', 'economical', 'prudent', 'sparing'],
    antonyms: ['wasteful', 'extravagant', 'spendthrift'],
  },
  {
    word: 'Paltry',
    partOfSpeech: 'adjective',
    meaning: 'Small or meager in amount or value; insignificant.',
    synonyms: ['meager', 'trivial', 'negligible', 'insignificant'],
    antonyms: ['substantial', 'considerable', 'ample'],
  },
  {
    word: 'Sterling',
    partOfSpeech: 'adjective',
    meaning: 'Of the highest quality; excellent.',
    synonyms: ['excellent', 'superb', 'exceptional', 'first-rate'],
    antonyms: ['poor', 'inferior', 'mediocre'],
  },
  {
    word: 'Limpid',
    partOfSpeech: 'adjective',
    meaning: 'Completely clear and transparent; easy to understand.',
    synonyms: ['clear', 'transparent', 'crystalline', 'lucid'],
    antonyms: ['murky', 'turbid', 'cloudy'],
  },
  {
    word: 'Accrue',
    partOfSpeech: 'verb',
    meaning: 'To accumulate or increase over time, especially of money or benefits.',
    synonyms: ['accumulate', 'amass', 'gather', 'build up'],
    antonyms: ['diminish', 'deplete', 'dwindle'],
  },
  {
    word: 'Desperado',
    partOfSpeech: 'noun',
    meaning: 'A desperate or reckless criminal, especially an outlaw.',
    synonyms: ['outlaw', 'criminal', 'bandit', 'fugitive'],
    antonyms: [],
  },
  {
    word: 'Joggle',
    partOfSpeech: 'verb',
    meaning: 'To shake or move slightly; to jolt.',
    synonyms: ['jiggle', 'jolt', 'shake', 'wobble'],
    antonyms: [],
  },
  {
    word: 'Paranoid',
    partOfSpeech: 'adjective',
    meaning: 'Exhibiting excessive or irrational distrust or suspicion of others.',
    synonyms: ['suspicious', 'distrustful', 'delusional'],
    antonyms: ['trusting', 'secure', 'confident'],
  },
  {
    word: 'Chandler',
    partOfSpeech: 'noun',
    meaning: 'A person who makes or sells candles; historically, a dealer in supplies or provisions.',
    synonyms: ['candlemaker'],
    antonyms: [],
  },
  {
    word: 'Cooper',
    partOfSpeech: 'noun',
    meaning: 'A person who makes or repairs wooden casks and barrels.',
    synonyms: ['barrel maker', 'cask maker'],
    antonyms: [],
  },
  {
    word: 'Frenzy',
    partOfSpeech: 'noun',
    meaning: 'A state of wild excitement or uncontrolled activity.',
    synonyms: ['mania', 'hysteria', 'uproar', 'agitation'],
    antonyms: ['calm', 'tranquility', 'composure'],
  },
  {
    word: 'Piquant',
    partOfSpeech: 'adjective',
    meaning: 'Having a pleasantly sharp taste or flavor; agreeably stimulating.',
    synonyms: ['spicy', 'tangy', 'zesty', 'sharp'],
    antonyms: ['bland', 'mild', 'insipid'],
  },
  {
    word: 'Tundra',
    partOfSpeech: 'noun',
    meaning: 'A vast, flat, treeless Arctic region with permanently frozen subsoil.',
    synonyms: [],
    antonyms: [],
  },
  {
    word: 'Condensation',
    partOfSpeech: 'noun',
    meaning: 'The process by which water vapor turns into liquid; the droplets formed this way.',
    synonyms: [],
    antonyms: ['evaporation'],
  },
  {
    word: 'Authenticity',
    partOfSpeech: 'noun',
    meaning: 'The quality of being genuine or real.',
    synonyms: ['genuineness', 'legitimacy', 'veracity'],
    antonyms: ['falseness', 'fraudulence'],
  },
  {
    word: 'Joule',
    partOfSpeech: 'noun',
    meaning: 'The SI unit of energy or work.',
    synonyms: [],
    antonyms: [],
  },
  {
    word: 'Watt',
    partOfSpeech: 'noun',
    meaning: 'The SI unit of power, equal to one joule per second.',
    synonyms: [],
    antonyms: [],
  },
  {
    word: 'Sycamore',
    partOfSpeech: 'noun',
    meaning: 'A large deciduous tree with broad leaves, common in North America and Europe.',
    synonyms: [],
    antonyms: [],
  },
  {
    word: 'Vassal',
    partOfSpeech: 'noun',
    meaning: 'Historically, a person granted land by a lord in exchange for allegiance and service; a subordinate.',
    synonyms: ['subordinate', 'subject', 'servant', 'dependent'],
    antonyms: ['lord', 'master', 'sovereign', 'overlord'],
  },
  {
    word: 'Infielder',
    partOfSpeech: 'noun',
    meaning: 'A baseball player positioned in the infield (first, second, third base, or shortstop).',
    synonyms: [],
    antonyms: ['outfielder'],
  },
  {
    word: 'Outfielder',
    partOfSpeech: 'noun',
    meaning: 'A baseball player positioned in the outfield.',
    synonyms: [],
    antonyms: ['infielder'],
  },
  {
    word: 'Stalwart',
    partOfSpeech: 'adjective',
    meaning: 'Loyal, reliable, and hardworking.',
    synonyms: ['loyal', 'steadfast', 'staunch', 'faithful'],
    antonyms: ['disloyal', 'unreliable', 'fickle'],
  },
  {
    word: 'Balmy',
    partOfSpeech: 'adjective',
    meaning: 'Pleasantly warm and mild, especially of weather.',
    synonyms: ['mild', 'pleasant', 'temperate', 'soothing'],
    antonyms: ['harsh', 'cold', 'frigid'],
  },
  {
    word: 'Torpid',
    partOfSpeech: 'adjective',
    meaning: 'Mentally or physically inactive; sluggish or dormant.',
    synonyms: ['lethargic', 'sluggish', 'dormant', 'listless'],
    antonyms: ['energetic', 'lively', 'vigorous'],
  },
  {
    word: 'Rancid',
    partOfSpeech: 'adjective',
    meaning: 'Having an unpleasant smell or taste from being old or stale.',
    synonyms: ['spoiled', 'foul', 'rotten', 'stale'],
    antonyms: ['fresh', 'wholesome'],
  },
  {
    word: 'Apathy',
    partOfSpeech: 'noun',
    meaning: 'Lack of interest, enthusiasm, or concern.',
    synonyms: ['indifference', 'unconcern', 'disinterest'],
    antonyms: ['enthusiasm', 'passion', 'interest'],
  },
  {
    word: 'Accolade',
    partOfSpeech: 'noun',
    meaning: 'An award or expression of praise for an achievement.',
    synonyms: ['award', 'honor', 'tribute', 'praise'],
    antonyms: ['criticism', 'condemnation', 'censure'],
  },
  {
    word: 'Affliction',
    partOfSpeech: 'noun',
    meaning: 'Something that causes pain or suffering; a condition of distress.',
    synonyms: ['suffering', 'hardship', 'ailment', 'torment'],
    antonyms: ['comfort', 'relief', 'blessing'],
  },
  {
    word: 'Malady',
    partOfSpeech: 'noun',
    meaning: 'A disease or ailment.',
    synonyms: ['illness', 'disease', 'ailment', 'sickness'],
    antonyms: ['health', 'wellness'],
  },
  {
    word: 'Skepticism',
    partOfSpeech: 'noun',
    meaning: 'A doubting or questioning attitude; disbelief.',
    synonyms: ['doubt', 'distrust', 'incredulity', 'cynicism'],
    antonyms: ['belief', 'faith', 'credulity'],
  },
  {
    word: 'Tumult',
    partOfSpeech: 'noun',
    meaning: 'A loud, confused noise or disturbance, especially caused by a crowd; a state of disorder.',
    synonyms: ['uproar', 'chaos', 'commotion', 'turmoil'],
    antonyms: ['calm', 'peace', 'order'],
  },
  {
    word: 'Quartz',
    partOfSpeech: 'noun',
    meaning: 'A hard, crystalline mineral composed of silicon dioxide.',
    synonyms: [],
    antonyms: [],
  },
  {
    word: 'Incensed',
    partOfSpeech: 'adjective',
    meaning: 'Very angry; enraged.',
    synonyms: ['furious', 'enraged', 'irate', 'livid'],
    antonyms: ['calm', 'pleased', 'content'],
  },
  {
    word: 'Skirmish',
    partOfSpeech: 'noun',
    meaning: 'A brief, minor fight or conflict, often between small groups.',
    synonyms: ['clash', 'scuffle', 'fight', 'tussle'],
    antonyms: ['truce', 'peace', 'ceasefire'],
  },
  {
    word: 'Triathlon',
    partOfSpeech: 'noun',
    meaning: 'An athletic contest of three events, typically swimming, cycling, and running.',
    synonyms: [],
    antonyms: [],
  },
  {
    word: 'Ungulate',
    partOfSpeech: 'noun',
    meaning: 'A hoofed mammal, such as a horse, deer, or cow.',
    synonyms: ['hoofed mammal'],
    antonyms: [],
  },
  {
    word: 'Abacus',
    partOfSpeech: 'noun',
    meaning: 'A manual calculating device using beads on rods or wires.',
    synonyms: ['counting frame'],
    antonyms: [],
  },
  {
    word: 'Hurdle',
    partOfSpeech: 'noun',
    meaning: 'An obstacle or barrier to jump over in a race; a difficulty to overcome.',
    synonyms: ['obstacle', 'barrier', 'impediment', 'hindrance'],
    antonyms: [],
  },
  {
    word: 'Isthmus',
    partOfSpeech: 'noun',
    meaning: 'A narrow strip of land connecting two larger areas of land, with water on both sides.',
    synonyms: ['neck of land'],
    antonyms: ['strait'],
  },
  {
    word: 'Strait',
    partOfSpeech: 'noun',
    meaning: 'A narrow passage of water connecting two larger bodies of water.',
    synonyms: ['channel', 'sound', 'narrows'],
    antonyms: ['isthmus'],
  },
  {
    word: 'Archipelago',
    partOfSpeech: 'noun',
    meaning: 'A group or chain of islands.',
    synonyms: ['island chain', 'island group'],
    antonyms: [],
  },
  {
    word: 'Ridge',
    partOfSpeech: 'noun',
    meaning: 'A long, narrow hilltop or mountain range; a raised strip on a surface.',
    synonyms: ['crest', 'ledge'],
    antonyms: ['valley', 'trough'],
  },
  {
    word: 'Conscription',
    partOfSpeech: 'noun',
    meaning: 'Compulsory enrollment for military service; the draft.',
    synonyms: ['draft', 'enlistment'],
    antonyms: [],
  },
  {
    word: 'Stoic',
    partOfSpeech: 'adjective',
    meaning: 'Enduring pain or hardship without showing feelings or complaining.',
    synonyms: ['impassive', 'unemotional', 'resilient'],
    antonyms: ['emotional', 'expressive', 'sensitive'],
  },
  {
    word: 'Murder',
    partOfSpeech: 'noun',
    meaning: 'The traditional collective noun for a group of crows (a "murder of crows") — distinct from its more common meaning, the crime of unlawfully killing someone.',
    synonyms: ['flock (of crows)'],
    antonyms: [],
  },
  {
    word: 'Equivocal',
    partOfSpeech: 'adjective',
    meaning: 'Open to more than one interpretation; deliberately vague or ambiguous.',
    synonyms: ['ambiguous', 'vague', 'uncertain', 'evasive'],
    antonyms: ['unambiguous', 'clear', 'definite'],
  },
  {
    word: 'Ambivalent',
    partOfSpeech: 'adjective',
    meaning: 'Having mixed or contradictory feelings about something.',
    synonyms: ['conflicted', 'uncertain', 'torn', 'indecisive'],
    antonyms: ['certain', 'decided', 'resolute'],
  },
  {
    word: 'Boorish',
    partOfSpeech: 'adjective',
    meaning: 'Rude, coarse, and unmannered.',
    synonyms: ['rude', 'crude', 'uncouth', 'coarse'],
    antonyms: ['polite', 'refined', 'courteous'],
  },
  {
    word: 'Inept',
    partOfSpeech: 'adjective',
    meaning: 'Having or showing no skill; clumsy or incompetent.',
    synonyms: ['incompetent', 'clumsy', 'bungling', 'unskillful'],
    antonyms: ['competent', 'skillful', 'adept', 'proficient'],
  },
  {
    word: 'Rash',
    partOfSpeech: 'adjective',
    meaning: 'Acting or done without careful consideration; hasty and reckless.',
    synonyms: ['reckless', 'impulsive', 'hasty', 'impetuous'],
    antonyms: ['cautious', 'careful', 'prudent'],
  },
  {
    word: 'Tepid',
    partOfSpeech: 'adjective',
    meaning: 'Only slightly warm; lukewarm; showing little enthusiasm.',
    synonyms: ['lukewarm', 'mild', 'unenthusiastic'],
    antonyms: ['hot', 'enthusiastic'],
  },
];
