/* ==========================================================================
   seed-words.js — a starter vocabulary list, added once to a new word bank
   (see Storage.seedWordsOnce in storage.js). Definitions/synonyms/antonyms
   written by hand rather than pulled from the dictionary APIs.
   Concrete/technical nouns without a real antonym (lavatory, silo, writ,
   cummerbund, ulcer, etc.) are left with an empty antonyms list rather than
   a forced/inaccurate pairing.

   Note: "Bouyant" (as given) is a common misspelling — stored here with
   its correct spelling, "Buoyant".
   ========================================================================== */

const SEED_WORDS = [
  {
    word: 'Defilement',
    partOfSpeech: 'noun',
    meaning: 'The act of making something impure, dirty, or corrupt; desecration of something pure or sacred.',
    synonyms: ['pollution', 'corruption', 'desecration', 'contamination'],
    antonyms: ['purification', 'cleansing'],
  },
  {
    word: 'Vilification',
    partOfSpeech: 'noun',
    meaning: 'Abusive or slanderous talk about someone; the act of speaking ill of a person.',
    synonyms: ['defamation', 'slander', 'denigration', 'disparagement'],
    antonyms: ['praise', 'commendation'],
  },
  {
    word: 'Ostracism',
    partOfSpeech: 'noun',
    meaning: 'Exclusion from a group or society; the act of shunning or banishing someone.',
    synonyms: ['exclusion', 'banishment', 'exile', 'shunning'],
    antonyms: ['inclusion', 'acceptance'],
  },
  {
    word: 'Trough',
    partOfSpeech: 'noun',
    meaning: 'A long, narrow, open container that holds food or water for animals; also the low point of a cycle or wave.',
    synonyms: ['manger', 'basin'],
    antonyms: ['peak', 'crest'],
  },
  {
    word: 'Lavatory',
    partOfSpeech: 'noun',
    meaning: 'A room or fixture equipped for washing and toileting; a bathroom.',
    synonyms: ['bathroom', 'restroom', 'washroom', 'latrine'],
    antonyms: [],
  },
  {
    word: 'Barracks',
    partOfSpeech: 'noun',
    meaning: 'A building or group of buildings used to house soldiers.',
    synonyms: ['quarters', 'garrison', 'encampment'],
    antonyms: [],
  },
  {
    word: 'Silo',
    partOfSpeech: 'noun',
    meaning: 'A tall tower or pit used to store grain or other bulk material.',
    synonyms: ['granary', 'storehouse', 'bin'],
    antonyms: [],
  },
  {
    word: 'Arsenal',
    partOfSpeech: 'noun',
    meaning: 'A collection or supply of weapons; a place where weapons are made or stored.',
    synonyms: ['armory', 'cache', 'stockpile'],
    antonyms: [],
  },
  {
    word: 'Arboretum',
    partOfSpeech: 'noun',
    meaning: 'A place, often a botanical garden, where trees and shrubs are grown for study and public display.',
    synonyms: ['botanical garden', 'tree garden'],
    antonyms: [],
  },
  {
    word: 'Cadet',
    partOfSpeech: 'noun',
    meaning: 'A student training to become an officer in the military or police.',
    synonyms: ['trainee', 'recruit', 'apprentice'],
    antonyms: [],
  },
  {
    word: 'Leery',
    partOfSpeech: 'adjective',
    meaning: 'Wary or suspicious; cautious about someone or something.',
    synonyms: ['wary', 'suspicious', 'distrustful', 'skeptical'],
    antonyms: ['trusting', 'confident', 'unsuspecting'],
  },
  {
    word: 'Embryonic',
    partOfSpeech: 'adjective',
    meaning: 'In an early, undeveloped stage; not yet fully formed.',
    synonyms: ['incipient', 'rudimentary', 'undeveloped', 'nascent'],
    antonyms: ['mature', 'developed', 'full-grown'],
  },
  {
    word: 'Ephemeral',
    partOfSpeech: 'adjective',
    meaning: 'Lasting for a very short time; fleeting.',
    synonyms: ['fleeting', 'transient', 'momentary', 'short-lived'],
    antonyms: ['permanent', 'everlasting', 'enduring'],
  },
  {
    word: 'Exalt',
    partOfSpeech: 'verb',
    meaning: 'To raise in rank, honor, or power; to praise highly.',
    synonyms: ['glorify', 'extol', 'elevate', 'revere'],
    antonyms: ['degrade', 'demean', 'disparage'],
  },
  {
    word: 'Fickle',
    partOfSpeech: 'adjective',
    meaning: 'Changing frequently, especially in loyalties or affections; inconstant.',
    synonyms: ['capricious', 'inconstant', 'volatile', 'changeable'],
    antonyms: ['steadfast', 'constant', 'loyal'],
  },
  {
    word: 'Flotsam',
    partOfSpeech: 'noun',
    meaning: 'Wreckage or debris found floating on the sea; discarded or scattered odds and ends.',
    synonyms: ['debris', 'wreckage', 'jetsam'],
    antonyms: [],
  },
  {
    word: 'Forge',
    partOfSpeech: 'verb',
    meaning: 'To form or shape something, especially through effort; or to make a fraudulent copy of something.',
    synonyms: ['fabricate', 'fashion', 'shape'],
    antonyms: [],
  },
  {
    word: 'Germane',
    partOfSpeech: 'adjective',
    meaning: 'Relevant to a subject under consideration; pertinent.',
    synonyms: ['relevant', 'pertinent', 'applicable', 'apt'],
    antonyms: ['irrelevant', 'unrelated', 'extraneous'],
  },
  {
    word: 'Glean',
    partOfSpeech: 'verb',
    meaning: 'To gather information or material bit by bit, often from various sources.',
    synonyms: ['gather', 'extract', 'collect', 'harvest'],
    antonyms: [],
  },
  {
    word: 'Inane',
    partOfSpeech: 'adjective',
    meaning: 'Silly, senseless, or lacking substance; foolish.',
    synonyms: ['senseless', 'foolish', 'vapid', 'absurd'],
    antonyms: ['sensible', 'profound', 'meaningful'],
  },
  {
    word: 'Ingress',
    partOfSpeech: 'noun',
    meaning: 'The act of entering; a means or place of entry.',
    synonyms: ['entry', 'entrance', 'access', 'admission'],
    antonyms: ['egress', 'exit', 'departure'],
  },
  {
    word: 'Innocuous',
    partOfSpeech: 'adjective',
    meaning: 'Not harmful or offensive; harmless.',
    synonyms: ['harmless', 'benign', 'inoffensive', 'safe'],
    antonyms: ['harmful', 'dangerous', 'noxious'],
  },
  {
    word: 'Laudatory',
    partOfSpeech: 'adjective',
    meaning: 'Expressing praise; commendatory.',
    synonyms: ['complimentary', 'commendatory', 'approving', 'admiring'],
    antonyms: ['critical', 'disparaging', 'derogatory'],
  },
  {
    word: 'Lucrative',
    partOfSpeech: 'adjective',
    meaning: 'Producing a great deal of profit; profitable.',
    synonyms: ['profitable', 'remunerative', 'gainful', 'moneymaking'],
    antonyms: ['unprofitable', 'worthless'],
  },
  {
    word: 'Mirage',
    partOfSpeech: 'noun',
    meaning: 'An optical illusion caused by atmospheric conditions; something illusory that appears real.',
    synonyms: ['illusion', 'hallucination', 'phantom', 'delusion'],
    antonyms: ['reality'],
  },
  {
    word: 'Null',
    partOfSpeech: 'adjective',
    meaning: 'Having no value, effect, or significance; nonexistent or invalid.',
    synonyms: ['void', 'invalid', 'nonexistent', 'empty'],
    antonyms: ['valid', 'significant', 'existent'],
  },
  {
    word: 'Overt',
    partOfSpeech: 'adjective',
    meaning: 'Done or shown openly; not hidden or secret.',
    synonyms: ['open', 'obvious', 'manifest', 'apparent'],
    antonyms: ['covert', 'hidden', 'secret', 'concealed'],
  },
  {
    word: 'Invaluable',
    partOfSpeech: 'adjective',
    meaning: 'Extremely useful or valuable; indispensable.',
    synonyms: ['priceless', 'indispensable', 'precious', 'essential'],
    antonyms: ['worthless', 'useless', 'dispensable'],
  },
  {
    word: 'Rife',
    partOfSpeech: 'adjective',
    meaning: 'Of common occurrence; widespread, especially something undesirable.',
    synonyms: ['widespread', 'abundant', 'prevalent', 'common'],
    antonyms: ['rare', 'scarce', 'uncommon'],
  },
  {
    word: 'Shroud',
    partOfSpeech: 'verb',
    meaning: 'To cover, conceal, or envelop something, hiding it from view.',
    synonyms: ['cover', 'veil', 'cloak', 'conceal'],
    antonyms: ['reveal', 'expose', 'uncover'],
  },
  {
    word: 'Tacit',
    partOfSpeech: 'adjective',
    meaning: 'Understood or implied without being stated directly.',
    synonyms: ['implied', 'unspoken', 'implicit', 'understood'],
    antonyms: ['explicit', 'stated', 'expressed'],
  },
  {
    word: 'Writ',
    partOfSpeech: 'noun',
    meaning: 'A formal written order issued by a court or other legal authority.',
    synonyms: ['decree', 'mandate', 'summons', 'order'],
    antonyms: [],
  },
  {
    word: 'Cummerbund',
    partOfSpeech: 'noun',
    meaning: 'A broad, pleated waist sash, often worn with men’s formal wear.',
    synonyms: ['sash', 'waistband'],
    antonyms: [],
  },
  {
    word: 'Ulcer',
    partOfSpeech: 'noun',
    meaning: 'An open sore on an internal or external body surface, caused by a break in tissue that fails to heal.',
    synonyms: ['sore', 'lesion', 'abscess'],
    antonyms: [],
  },
  {
    word: 'Buoyant',
    partOfSpeech: 'adjective',
    meaning: 'Cheerful and optimistic, quick to recover from setbacks; also, able to float.',
    synonyms: ['cheerful', 'optimistic', 'resilient', 'upbeat'],
    antonyms: ['despondent', 'gloomy', 'dejected'],
  },
];
