/* ==========================================================================
   seed-words.js — a starter vocabulary list, added once to a new word bank
   (see Storage.seedWordsOnce in storage.js). Definitions/synonyms/antonyms
   written by hand rather than pulled from the dictionary APIs.
   Concrete/technical nouns without a real antonym (lavatory, silo, writ,
   cummerbund, ulcer, etc.) are left with an empty antonyms list rather than
   a forced/inaccurate pairing.

   Note: "Bouyant" (as given) is a common misspelling — stored here with
   its correct spelling, "Buoyant".
   ========================================================================== */

const SEED_WORDS = [
  {
    word: 'Defilement',
    partOfSpeech: 'noun',
    meaning: 'The act of making something impure, dirty, or corrupt; desecration of something pure or sacred.',
    synonyms: ['pollution', 'corruption', 'desecration', 'contamination'],
    antonyms: ['purification', 'cleansing'],
  },
  {
    word: 'Vilification',
    partOfSpeech: 'noun',
    meaning: 'Abusive or slanderous talk about someone; the act of speaking ill of a person.',
    synonyms: ['defamation', 'slander', 'denigration', 'disparagement'],
    antonyms: ['praise', 'commendation'],
  },
  {
    word: 'Ostracism',
    partOfSpeech: 'noun',
    meaning: 'Exclusion from a group or society; the act of shunning or banishing someone.',
    synonyms: ['exclusion', 'banishment', 'exile', 'shunning'],
    antonyms: ['inclusion', 'acceptance'],
  },
  {
    word: 'Trough',
    partOfSpeech: 'noun',
    meaning: 'A long, narrow, open container that holds food or water for animals; also the low point of a cycle or wave.',
    synonyms: ['manger', 'basin'],
    antonyms: ['peak', 'crest'],
  },
  {
    word: 'Lavatory',
    partOfSpeech: 'noun',
    meaning: 'A room or fixture equipped for washing and toileting; a bathroom.',
    synonyms: ['bathroom', 'restroom', 'washroom', 'latrine'],
    antonyms: [],
  },
  {
    word: 'Barracks',
    partOfSpeech: 'noun',
    meaning: 'A building or group of buildings used to house soldiers.',
    synonyms: ['quarters', 'garrison', 'encampment'],
    antonyms: [],
  },
  {
    word: 'Silo',
    partOfSpeech: 'noun',
    meaning: 'A tall tower or pit used to store grain or other bulk material.',
    synonyms: ['granary', 'storehouse', 'bin'],
    antonyms: [],
  },
  {
    word: 'Arsenal',
    partOfSpeech: 'noun',
    meaning: 'A collection or supply of weapons; a place where weapons are made or stored.',
    synonyms: ['armory', 'cache', 'stockpile'],
    antonyms: [],
  },
  {
    word: 'Arboretum',
    partOfSpeech: 'noun',
    meaning: 'A place, often a botanical garden, where trees and shrubs are grown for study and public display.',
    synonyms: ['botanical garden', 'tree garden'],
    antonyms: [],
  },
  {
    word: 'Cadet',
    partOfSpeech: 'noun',
    meaning: 'A student training to become an officer in the military or police.',
    synonyms: ['trainee', 'recruit', 'apprentice'],
    antonyms: [],
  },
  {
    word: 'Leery',
    partOfSpeech: 'adjective',
    meaning: 'Wary or suspicious; cautious about someone or something.',
    synonyms: ['wary', 'suspicious', 'distrustful', 'skeptical'],
    antonyms: ['trusting', 'confident', 'unsuspecting'],
  },
  {
    word: 'Embryonic',
    partOfSpeech: 'adjective',
    meaning: 'In an early, undeveloped stage; not yet fully formed.',
    synonyms: ['incipient', 'rudimentary', 'undeveloped', 'nascent'],
    antonyms: ['mature', 'developed', 'full-grown'],
  },
  {
    word: 'Ephemeral',
    partOfSpeech: 'adjective',
    meaning: 'Lasting for a very short time; fleeting.',
    synonyms: ['fleeting', 'transient', 'momentary', 'short-lived'],
    antonyms: ['permanent', 'everlasting', 'enduring'],
  },
  {
    word: 'Exalt',
    partOfSpeech: 'verb',
    meaning: 'To raise in rank, honor, or power; to praise highly.',
    synonyms: ['glorify', 'extol', 'elevate', 'revere'],
    antonyms: ['degrade', 'demean', 'disparage'],
  },
  {
    word: 'Fickle',
    partOfSpeech: 'adjective',
    meaning: 'Changing frequently, especially in loyalties or affections; inconstant.',
    synonyms: ['capricious', 'inconstant', 'volatile', 'changeable'],
    antonyms: ['steadfast', 'constant', 'loyal'],
  },
  {
    word: 'Flotsam',
    partOfSpeech: 'noun',
    meaning: 'Wreckage or debris found floating on the sea; discarded or scattered odds and ends.',
    synonyms: ['debris', 'wreckage', 'jetsam'],
    antonyms: [],
  },
  {
    word: 'Forge',
    partOfSpeech: 'verb',
    meaning: 'To form or shape something, especially through effort; or to make a fraudulent copy of something.',
    synonyms: ['fabricate', 'fashion', 'shape'],
    antonyms: [],
  },
  {
    word: 'Germane',
    partOfSpeech: 'adjective',
    meaning: 'Relevant to a subject under consideration; pertinent.',
    synonyms: ['relevant', 'pertinent', 'applicable', 'apt'],
    antonyms: ['irrelevant', 'unrelated', 'extraneous'],
  },
  {
    word: 'Glean',
    partOfSpeech: 'verb',
    meaning: 'To gather information or material bit by bit, often from various sources.',
    synonyms: ['gather', 'extract', 'collect', 'harvest'],
    antonyms: [],
  },
  {
    word: 'Inane',
    partOfSpeech: 'adjective',
    meaning: 'Silly, senseless, or lacking substance; foolish.',
    synonyms: ['senseless', 'foolish', 'vapid', 'absurd'],
    antonyms: ['sensible', 'profound', 'meaningful'],
  },
  {
    word: 'Ingress',
    partOfSpeech: 'noun',
    meaning: 'The act of entering; a means or place of entry.',
    synonyms: ['entry', 'entrance', 'access', 'admission'],
    antonyms: ['egress', 'exit', 'departure'],
  },
  {
    word: 'Innocuous',
    partOfSpeech: 'adjective',
    meaning: 'Not harmful or offensive; harmless.',
    synonyms: ['harmless', 'benign', 'inoffensive', 'safe'],
    antonyms: ['harmful', 'dangerous', 'noxious'],
  },
  {
    word: 'Laudatory',
    partOfSpeech: 'adjective',
    meaning: 'Expressing praise; commendatory.',
    synonyms: ['complimentary', 'commendatory', 'approving', 'admiring'],
    antonyms: ['critical', 'disparaging', 'derogatory'],
  },
  {
    word: 'Lucrative',
    partOfSpeech: 'adjective',
    meaning: 'Producing a great deal of profit; profitable.',
    synonyms: ['profitable', 'remunerative', 'gainful', 'moneymaking'],
    antonyms: ['unprofitable', 'worthless'],
  },
  {
    word: 'Mirage',
    partOfSpeech: 'noun',
    meaning: 'An optical illusion caused by atmospheric conditions; something illusory that appears real.',
    synonyms: ['illusion', 'hallucination', 'phantom', 'delusion'],
    antonyms: ['reality'],
  },
  {
    word: 'Null',
    partOfSpeech: 'adjective',
    meaning: 'Having no value, effect, or significance; nonexistent or invalid.',
    synonyms: ['void', 'invalid', 'nonexistent', 'empty'],
    antonyms: ['valid', 'significant', 'existent'],
  },
  {
    word: 'Overt',
    partOfSpeech: 'adjective',
    meaning: 'Done or shown openly; not hidden or secret.',
    synonyms: ['open', 'obvious', 'manifest', 'apparent'],
    antonyms: ['covert', 'hidden', 'secret', 'concealed'],
  },
  {
    word: 'Invaluable',
    partOfSpeech: 'adjective',
    meaning: 'Extremely useful or valuable; indispensable.',
    synonyms: ['priceless', 'indispensable', 'precious', 'essential'],
    antonyms: ['worthless', 'useless', 'dispensable'],
  },
  {
    word: 'Rife',
    partOfSpeech: 'adjective',
    meaning: 'Of common occurrence; widespread, especially something undesirable.',
    synonyms: ['widespread', 'abundant', 'prevalent', 'common'],
    antonyms: ['rare', 'scarce', 'uncommon'],
  },
  {
    word: 'Shroud',
    partOfSpeech: 'verb',
    meaning: 'To cover, conceal, or envelop something, hiding it from view.',
    synonyms: ['cover', 'veil', 'cloak', 'conceal'],
    antonyms: ['reveal', 'expose', 'uncover'],
  },
  {
    word: 'Tacit',
    partOfSpeech: 'adjective',
    meaning: 'Understood or implied without being stated directly.',
    synonyms: ['implied', 'unspoken', 'implicit', 'understood'],
    antonyms: ['explicit', 'stated', 'expressed'],
  },
  {
    word: 'Writ',
    partOfSpeech: 'noun',
    meaning: 'A formal written order issued by a court or other legal authority.',
    synonyms: ['decree', 'mandate', 'summons', 'order'],
    antonyms: [],
  },
  {
    word: 'Cummerbund',
    partOfSpeech: 'noun',
    meaning: 'A broad, pleated waist sash, often worn with men’s formal wear.',
    synonyms: ['sash', 'waistband'],
    antonyms: [],
  },
  {
    word: 'Ulcer',
    partOfSpeech: 'noun',
    meaning: 'An open sore on an internal or external body surface, caused by a break in tissue that fails to heal.',
    synonyms: ['sore', 'lesion', 'abscess'],
    antonyms: [],
  },
  {
    word: 'Buoyant',
    partOfSpeech: 'adjective',
    meaning: 'Cheerful and optimistic, quick to recover from setbacks; also, able to float.',
    synonyms: ['cheerful', 'optimistic', 'resilient', 'upbeat'],
    antonyms: ['despondent', 'gloomy', 'dejected'],
  },
  {
    word: 'Scrutinize',
    partOfSpeech: 'verb',
    meaning: 'To examine or inspect something closely and thoroughly.',
    synonyms: ['examine', 'inspect', 'analyze', 'study'],
    antonyms: ['ignore', 'overlook', 'skim'],
  },
  {
    word: 'Agony',
    partOfSpeech: 'noun',
    meaning: 'Extreme physical or mental suffering.',
    synonyms: ['anguish', 'torment', 'suffering', 'distress'],
    antonyms: ['comfort', 'relief', 'bliss'],
  },
  {
    word: 'Sanguine',
    partOfSpeech: 'adjective',
    meaning: 'Optimistic or positive, especially in a difficult situation.',
    synonyms: ['optimistic', 'hopeful', 'positive', 'confident'],
    antonyms: ['pessimistic', 'gloomy', 'despondent'],
  },
  {
    word: 'Inebriated',
    partOfSpeech: 'adjective',
    meaning: 'Drunk; intoxicated with alcohol.',
    synonyms: ['intoxicated', 'drunk', 'tipsy'],
    antonyms: ['sober', 'clearheaded'],
  },
  {
    word: 'Nihilistic',
    partOfSpeech: 'adjective',
    meaning: 'Believing that life is meaningless and traditional values are unfounded.',
    synonyms: ['cynical', 'skeptical', 'pessimistic'],
    antonyms: ['idealistic', 'optimistic'],
  },
  {
    word: 'Intrepid',
    partOfSpeech: 'adjective',
    meaning: 'Fearless and adventurous, especially in the face of danger.',
    synonyms: ['fearless', 'brave', 'bold', 'courageous'],
    antonyms: ['timid', 'cowardly', 'fearful'],
  },
  {
    word: 'Parsimonious',
    partOfSpeech: 'adjective',
    meaning: 'Extremely unwilling to spend money or use resources; stingy.',
    synonyms: ['stingy', 'miserly', 'frugal', 'tightfisted'],
    antonyms: ['generous', 'extravagant', 'lavish'],
  },
  {
    word: 'Thrifty',
    partOfSpeech: 'adjective',
    meaning: 'Careful and prudent with money; economical.',
    synonyms: ['frugal', 'economical', 'prudent', 'sparing'],
    antonyms: ['wasteful', 'extravagant', 'spendthrift'],
  },
  {
    word: 'Paltry',
    partOfSpeech: 'adjective',
    meaning: 'Small or meager in amount or value; insignificant.',
    synonyms: ['meager', 'trivial', 'negligible', 'insignificant'],
    antonyms: ['substantial', 'considerable', 'ample'],
  },
  {
    word: 'Sterling',
    partOfSpeech: 'adjective',
    meaning: 'Of the highest quality; excellent.',
    synonyms: ['excellent', 'superb', 'exceptional', 'first-rate'],
    antonyms: ['poor', 'inferior', 'mediocre'],
  },
  {
    word: 'Limpid',
    partOfSpeech: 'adjective',
    meaning: 'Completely clear and transparent; easy to understand.',
    synonyms: ['clear', 'transparent', 'crystalline', 'lucid'],
    antonyms: ['murky', 'turbid', 'cloudy'],
  },
  {
    word: 'Accrue',
    partOfSpeech: 'verb',
    meaning: 'To accumulate or increase over time, especially of money or benefits.',
    synonyms: ['accumulate', 'amass', 'gather', 'build up'],
    antonyms: ['diminish', 'deplete', 'dwindle'],
  },
  {
    word: 'Desperado',
    partOfSpeech: 'noun',
    meaning: 'A desperate or reckless criminal, especially an outlaw.',
    synonyms: ['outlaw', 'criminal', 'bandit', 'fugitive'],
    antonyms: [],
  },
  {
    word: 'Joggle',
    partOfSpeech: 'verb',
    meaning: 'To shake or move slightly; to jolt.',
    synonyms: ['jiggle', 'jolt', 'shake', 'wobble'],
    antonyms: [],
  },
  {
    word: 'Paranoid',
    partOfSpeech: 'adjective',
    meaning: 'Exhibiting excessive or irrational distrust or suspicion of others.',
    synonyms: ['suspicious', 'distrustful', 'delusional'],
    antonyms: ['trusting', 'secure', 'confident'],
  },
  {
    word: 'Chandler',
    partOfSpeech: 'noun',
    meaning: 'A person who makes or sells candles; historically, a dealer in supplies or provisions.',
    synonyms: ['candlemaker'],
    antonyms: [],
  },
  {
    word: 'Cooper',
    partOfSpeech: 'noun',
    meaning: 'A person who makes or repairs wooden casks and barrels.',
    synonyms: ['barrel maker', 'cask maker'],
    antonyms: [],
  },
  {
    word: 'Frenzy',
    partOfSpeech: 'noun',
    meaning: 'A state of wild excitement or uncontrolled activity.',
    synonyms: ['mania', 'hysteria', 'uproar', 'agitation'],
    antonyms: ['calm', 'tranquility', 'composure'],
  },
  {
    word: 'Piquant',
    partOfSpeech: 'adjective',
    meaning: 'Having a pleasantly sharp taste or flavor; agreeably stimulating.',
    synonyms: ['spicy', 'tangy', 'zesty', 'sharp'],
    antonyms: ['bland', 'mild', 'insipid'],
  },
  {
    word: 'Tundra',
    partOfSpeech: 'noun',
    meaning: 'A vast, flat, treeless Arctic region with permanently frozen subsoil.',
    synonyms: [],
    antonyms: [],
  },
  {
    word: 'Condensation',
    partOfSpeech: 'noun',
    meaning: 'The process by which water vapor turns into liquid; the droplets formed this way.',
    synonyms: [],
    antonyms: ['evaporation'],
  },
  {
    word: 'Authenticity',
    partOfSpeech: 'noun',
    meaning: 'The quality of being genuine or real.',
    synonyms: ['genuineness', 'legitimacy', 'veracity'],
    antonyms: ['falseness', 'fraudulence'],
  },
  {
    word: 'Joule',
    partOfSpeech: 'noun',
    meaning: 'The SI unit of energy or work.',
    synonyms: [],
    antonyms: [],
  },
  {
    word: 'Watt',
    partOfSpeech: 'noun',
    meaning: 'The SI unit of power, equal to one joule per second.',
    synonyms: [],
    antonyms: [],
  },
  {
    word: 'Sycamore',
    partOfSpeech: 'noun',
    meaning: 'A large deciduous tree with broad leaves, common in North America and Europe.',
    synonyms: [],
    antonyms: [],
  },
  {
    word: 'Vassal',
    partOfSpeech: 'noun',
    meaning: 'Historically, a person granted land by a lord in exchange for allegiance and service; a subordinate.',
    synonyms: ['subordinate', 'subject', 'servant', 'dependent'],
    antonyms: ['lord', 'master', 'sovereign', 'overlord'],
  },
  {
    word: 'Infielder',
    partOfSpeech: 'noun',
    meaning: 'A baseball player positioned in the infield (first, second, third base, or shortstop).',
    synonyms: [],
    antonyms: ['outfielder'],
  },
  {
    word: 'Outfielder',
    partOfSpeech: 'noun',
    meaning: 'A baseball player positioned in the outfield.',
    synonyms: [],
    antonyms: ['infielder'],
  },
  {
    word: 'Stalwart',
    partOfSpeech: 'adjective',
    meaning: 'Loyal, reliable, and hardworking.',
    synonyms: ['loyal', 'steadfast', 'staunch', 'faithful'],
    antonyms: ['disloyal', 'unreliable', 'fickle'],
  },
  {
    word: 'Balmy',
    partOfSpeech: 'adjective',
    meaning: 'Pleasantly warm and mild, especially of weather.',
    synonyms: ['mild', 'pleasant', 'temperate', 'soothing'],
    antonyms: ['harsh', 'cold', 'frigid'],
  },
  {
    word: 'Torpid',
    partOfSpeech: 'adjective',
    meaning: 'Mentally or physically inactive; sluggish or dormant.',
    synonyms: ['lethargic', 'sluggish', 'dormant', 'listless'],
    antonyms: ['energetic', 'lively', 'vigorous'],
  },
  {
    word: 'Rancid',
    partOfSpeech: 'adjective',
    meaning: 'Having an unpleasant smell or taste from being old or stale.',
    synonyms: ['spoiled', 'foul', 'rotten', 'stale'],
    antonyms: ['fresh', 'wholesome'],
  },
  {
    word: 'Apathy',
    partOfSpeech: 'noun',
    meaning: 'Lack of interest, enthusiasm, or concern.',
    synonyms: ['indifference', 'unconcern', 'disinterest'],
    antonyms: ['enthusiasm', 'passion', 'interest'],
  },
  {
    word: 'Accolade',
    partOfSpeech: 'noun',
    meaning: 'An award or expression of praise for an achievement.',
    synonyms: ['award', 'honor', 'tribute', 'praise'],
    antonyms: ['criticism', 'condemnation', 'censure'],
  },
  {
    word: 'Affliction',
    partOfSpeech: 'noun',
    meaning: 'Something that causes pain or suffering; a condition of distress.',
    synonyms: ['suffering', 'hardship', 'ailment', 'torment'],
    antonyms: ['comfort', 'relief', 'blessing'],
  },
  {
    word: 'Malady',
    partOfSpeech: 'noun',
    meaning: 'A disease or ailment.',
    synonyms: ['illness', 'disease', 'ailment', 'sickness'],
    antonyms: ['health', 'wellness'],
  },
  {
    word: 'Skepticism',
    partOfSpeech: 'noun',
    meaning: 'A doubting or questioning attitude; disbelief.',
    synonyms: ['doubt', 'distrust', 'incredulity', 'cynicism'],
    antonyms: ['belief', 'faith', 'credulity'],
  },
  {
    word: 'Tumult',
    partOfSpeech: 'noun',
    meaning: 'A loud, confused noise or disturbance, especially caused by a crowd; a state of disorder.',
    synonyms: ['uproar', 'chaos', 'commotion', 'turmoil'],
    antonyms: ['calm', 'peace', 'order'],
  },
  {
    word: 'Quartz',
    partOfSpeech: 'noun',
    meaning: 'A hard, crystalline mineral composed of silicon dioxide.',
    synonyms: [],
    antonyms: [],
  },
  {
    word: 'Incensed',
    partOfSpeech: 'adjective',
    meaning: 'Very angry; enraged.',
    synonyms: ['furious', 'enraged', 'irate', 'livid'],
    antonyms: ['calm', 'pleased', 'content'],
  },
  {
    word: 'Skirmish',
    partOfSpeech: 'noun',
    meaning: 'A brief, minor fight or conflict, often between small groups.',
    synonyms: ['clash', 'scuffle', 'fight', 'tussle'],
    antonyms: ['truce', 'peace', 'ceasefire'],
  },
  {
    word: 'Triathlon',
    partOfSpeech: 'noun',
    meaning: 'An athletic contest of three events, typically swimming, cycling, and running.',
    synonyms: [],
    antonyms: [],
  },
  {
    word: 'Ungulate',
    partOfSpeech: 'noun',
    meaning: 'A hoofed mammal, such as a horse, deer, or cow.',
    synonyms: ['hoofed mammal'],
    antonyms: [],
  },
  {
    word: 'Abacus',
    partOfSpeech: 'noun',
    meaning: 'A manual calculating device using beads on rods or wires.',
    synonyms: ['counting frame'],
    antonyms: [],
  },
  {
    word: 'Hurdle',
    partOfSpeech: 'noun',
    meaning: 'An obstacle or barrier to jump over in a race; a difficulty to overcome.',
    synonyms: ['obstacle', 'barrier', 'impediment', 'hindrance'],
    antonyms: [],
  },
  {
    word: 'Isthmus',
    partOfSpeech: 'noun',
    meaning: 'A narrow strip of land connecting two larger areas of land, with water on both sides.',
    synonyms: ['neck of land'],
    antonyms: ['strait'],
  },
  {
    word: 'Strait',
    partOfSpeech: 'noun',
    meaning: 'A narrow passage of water connecting two larger bodies of water.',
    synonyms: ['channel', 'sound', 'narrows'],
    antonyms: ['isthmus'],
  },
  {
    word: 'Archipelago',
    partOfSpeech: 'noun',
    meaning: 'A group or chain of islands.',
    synonyms: ['island chain', 'island group'],
    antonyms: [],
  },
  {
    word: 'Ridge',
    partOfSpeech: 'noun',
    meaning: 'A long, narrow hilltop or mountain range; a raised strip on a surface.',
    synonyms: ['crest', 'ledge'],
    antonyms: ['valley', 'trough'],
  },
  {
    word: 'Conscription',
    partOfSpeech: 'noun',
    meaning: 'Compulsory enrollment for military service; the draft.',
    synonyms: ['draft', 'enlistment'],
    antonyms: [],
  },
  {
    word: 'Stoic',
    partOfSpeech: 'adjective',
    meaning: 'Enduring pain or hardship without showing feelings or complaining.',
    synonyms: ['impassive', 'unemotional', 'resilient'],
    antonyms: ['emotional', 'expressive', 'sensitive'],
  },
  {
    word: 'Murder',
    partOfSpeech: 'noun',
    meaning: 'The traditional collective noun for a group of crows (a "murder of crows") — distinct from its more common meaning, the crime of unlawfully killing someone.',
    synonyms: ['flock (of crows)'],
    antonyms: [],
  },
  {
    word: 'Equivocal',
    partOfSpeech: 'adjective',
    meaning: 'Open to more than one interpretation; deliberately vague or ambiguous.',
    synonyms: ['ambiguous', 'vague', 'uncertain', 'evasive'],
    antonyms: ['unambiguous', 'clear', 'definite'],
  },
  {
    word: 'Ambivalent',
    partOfSpeech: 'adjective',
    meaning: 'Having mixed or contradictory feelings about something.',
    synonyms: ['conflicted', 'uncertain', 'torn', 'indecisive'],
    antonyms: ['certain', 'decided', 'resolute'],
  },
  {
    word: 'Boorish',
    partOfSpeech: 'adjective',
    meaning: 'Rude, coarse, and unmannered.',
    synonyms: ['rude', 'crude', 'uncouth', 'coarse'],
    antonyms: ['polite', 'refined', 'courteous'],
  },
  {
    word: 'Inept',
    partOfSpeech: 'adjective',
    meaning: 'Having or showing no skill; clumsy or incompetent.',
    synonyms: ['incompetent', 'clumsy', 'bungling', 'unskillful'],
    antonyms: ['competent', 'skillful', 'adept', 'proficient'],
  },
  {
    word: 'Rash',
    partOfSpeech: 'adjective',
    meaning: 'Acting or done without careful consideration; hasty and reckless.',
    synonyms: ['reckless', 'impulsive', 'hasty', 'impetuous'],
    antonyms: ['cautious', 'careful', 'prudent'],
  },
  {
    word: 'Tepid',
    partOfSpeech: 'adjective',
    meaning: 'Only slightly warm; lukewarm; showing little enthusiasm.',
    synonyms: ['lukewarm', 'mild', 'unenthusiastic'],
    antonyms: ['hot', 'enthusiastic'],
  },
  {
    word: 'Hallow',
    partOfSpeech: 'verb',
    meaning: 'To honor as holy; to sanctify or greatly respect.',
    synonyms: ['sanctify', 'consecrate', 'revere', 'venerate'],
    antonyms: ['desecrate', 'defile', 'profane'],
  },
  {
    word: 'Glib',
    partOfSpeech: 'adjective',
    meaning: 'Fluent and articulate in a way that suggests insincerity or a lack of thought.',
    synonyms: ['fluent', 'slick', 'smooth-talking', 'superficial'],
    antonyms: ['sincere', 'genuine', 'thoughtful'],
  },
  {
    word: 'Tenacious',
    partOfSpeech: 'adjective',
    meaning: 'Holding firmly to something; persistent and not easily stopped.',
    synonyms: ['persistent', 'resolute', 'determined', 'steadfast'],
    antonyms: ['irresolute', 'yielding', 'weak-willed'],
  },
  {
    word: 'Profound',
    partOfSpeech: 'adjective',
    meaning: 'Very great or intense; showing deep insight or understanding.',
    synonyms: ['deep', 'intense', 'insightful', 'thoughtful'],
    antonyms: ['superficial', 'shallow', 'trivial'],
  },
  {
    word: 'Convergence',
    partOfSpeech: 'noun',
    meaning: 'The process of coming together toward a common point; merging.',
    synonyms: ['merging', 'meeting', 'confluence'],
    antonyms: ['divergence', 'separation'],
  },
  {
    word: 'Oblivion',
    partOfSpeech: 'noun',
    meaning: 'The state of being unaware or unconscious; the state of being forgotten.',
    synonyms: ['obscurity', 'nonexistence', 'unawareness'],
    antonyms: ['awareness', 'fame', 'remembrance'],
  },
  {
    word: 'Convolution',
    partOfSpeech: 'noun',
    meaning: 'A twist or curve, especially one of many; complexity or intricacy.',
    synonyms: ['complexity', 'intricacy', 'twist'],
    antonyms: ['simplicity', 'straightforwardness'],
  },
  {
    word: 'Junction',
    partOfSpeech: 'noun',
    meaning: 'A point where two or more things join or meet, such as roads or railways.',
    synonyms: ['intersection', 'joint', 'crossing'],
    antonyms: [],
  },
  {
    word: 'Conciliate',
    partOfSpeech: 'verb',
    meaning: 'To overcome distrust or hostility; to placate or win over.',
    synonyms: ['appease', 'placate', 'pacify', 'mollify'],
    antonyms: ['antagonize', 'provoke', 'alienate'],
  },
  {
    word: 'Enterprise',
    partOfSpeech: 'noun',
    meaning: 'A project or undertaking, especially a bold or complex one.',
    synonyms: ['venture', 'undertaking', 'initiative'],
    antonyms: [],
  },
  {
    word: 'Venture',
    partOfSpeech: 'noun',
    meaning: 'A risky or daring undertaking, especially in business.',
    synonyms: ['undertaking', 'enterprise', 'endeavor'],
    antonyms: [],
  },
  {
    word: 'Incision',
    partOfSpeech: 'noun',
    meaning: 'A cut, especially one made during surgery.',
    synonyms: ['cut', 'slit', 'gash'],
    antonyms: [],
  },
  {
    word: 'Incisive',
    partOfSpeech: 'adjective',
    meaning: 'Clear, sharp, and direct, especially in thought or expression.',
    synonyms: ['sharp', 'penetrating', 'perceptive', 'acute'],
    antonyms: ['vague', 'dull', 'superficial'],
  },
  {
    word: 'Inundate',
    partOfSpeech: 'verb',
    meaning: 'To overwhelm with a large amount of something, especially water, tasks, or requests; to flood.',
    synonyms: ['flood', 'overwhelm', 'swamp', 'deluge'],
    antonyms: [],
  },

  // -- Imported from ~/Downloads/vocabulary_word_list.pdf (219 words; 6 exact
  // duplicates already above — Fickle, Frenzy, Glib, Profound, Tenacious,
  // Tepid — are skipped here since mergeWords would drop them anyway).
  // Definitions adapted from the PDF (trimmed to one primary sense where the
  // source gave several); synonyms/antonyms added by hand.
  {
    word: 'Adjunct',
    partOfSpeech: 'noun',
    meaning: 'Something or someone associated with another but in a secondary, subordinate position.',
    synonyms: ['accessory', 'supplement', 'addition'],
    antonyms: ['principal'],
  },
  {
    word: 'Admonish',
    partOfSpeech: 'verb',
    meaning: 'To gently scold or warn; to urge to duty.',
    synonyms: ['reprimand', 'scold', 'warn', 'caution'],
    antonyms: ['praise', 'commend'],
  },
  {
    word: 'Affable',
    partOfSpeech: 'adjective',
    meaning: 'Pleasantly easy to get along with; friendly and warm.',
    synonyms: ['amiable', 'friendly', 'genial', 'cordial'],
    antonyms: ['unfriendly', 'hostile', 'aloof'],
  },
  {
    word: 'Aghast',
    partOfSpeech: 'adjective',
    meaning: 'Overcome with shock, horror, or amazement.',
    synonyms: ['horrified', 'shocked', 'appalled', 'astounded'],
    antonyms: ['unfazed', 'unmoved'],
  },
  {
    word: 'Alleviate',
    partOfSpeech: 'verb',
    meaning: 'To make easier to bear; to lessen.',
    synonyms: ['relieve', 'ease', 'lessen', 'mitigate'],
    antonyms: ['worsen', 'aggravate', 'intensify'],
  },
  {
    word: 'Aloof',
    partOfSpeech: 'adjective',
    meaning: 'Distant or reserved in relations with other people.',
    synonyms: ['distant', 'reserved', 'detached', 'standoffish'],
    antonyms: ['friendly', 'warm', 'sociable'],
  },
  {
    word: 'Altruistic',
    partOfSpeech: 'adjective',
    meaning: 'Concerned for the welfare of others; selfless.',
    synonyms: ['selfless', 'generous', 'charitable', 'unselfish'],
    antonyms: ['selfish', 'egotistical'],
  },
  {
    word: 'Amend',
    partOfSpeech: 'verb',
    meaning: 'To improve or alter, especially by formal procedure.',
    synonyms: ['revise', 'modify', 'alter', 'improve'],
    antonyms: [],
  },
  {
    word: 'Amorphous',
    partOfSpeech: 'adjective',
    meaning: 'Lacking a specific shape or form.',
    synonyms: ['shapeless', 'formless', 'unstructured'],
    antonyms: ['defined', 'structured', 'shaped'],
  },
  {
    word: 'Animosity',
    partOfSpeech: 'noun',
    meaning: 'A feeling of ill will or intense dislike.',
    synonyms: ['hostility', 'resentment', 'antagonism', 'enmity'],
    antonyms: ['goodwill', 'affection', 'friendliness'],
  },
  {
    word: 'Annihilate',
    partOfSpeech: 'verb',
    meaning: 'To destroy completely.',
    synonyms: ['obliterate', 'destroy', 'demolish', 'eradicate'],
    antonyms: ['create', 'build', 'preserve'],
  },
  {
    word: 'Ardent',
    partOfSpeech: 'adjective',
    meaning: 'Characterized by passion or intense enthusiasm.',
    synonyms: ['passionate', 'fervent', 'zealous', 'enthusiastic'],
    antonyms: ['indifferent', 'apathetic', 'half-hearted'],
  },
  {
    word: 'Articulate',
    partOfSpeech: 'adjective',
    meaning: 'Well-spoken and able to express ideas clearly.',
    synonyms: ['eloquent', 'fluent', 'lucid', 'expressive'],
    antonyms: ['inarticulate', 'tongue-tied'],
  },
  {
    word: 'Artifice',
    partOfSpeech: 'noun',
    meaning: 'Clever trickery used to deceive.',
    synonyms: ['trickery', 'cunning', 'ruse', 'deception'],
    antonyms: ['honesty', 'candor', 'sincerity'],
  },
  {
    word: 'Ascertain',
    partOfSpeech: 'verb',
    meaning: 'To find out or discover something with certainty.',
    synonyms: ['determine', 'discover', 'establish', 'confirm'],
    antonyms: [],
  },
  {
    word: 'Astute',
    partOfSpeech: 'adjective',
    meaning: 'Shrewd and perceptive; able to understand quickly.',
    synonyms: ['shrewd', 'perceptive', 'sharp', 'discerning'],
    antonyms: ['obtuse', 'naive', 'dull'],
  },
  {
    word: 'Atrocity',
    partOfSpeech: 'noun',
    meaning: 'An extremely cruel or brutal act.',
    synonyms: ['outrage', 'horror', 'brutality'],
    antonyms: [],
  },
  {
    word: 'Audacity',
    partOfSpeech: 'noun',
    meaning: 'Boldness or daring, especially with disregard for personal safety or social convention.',
    synonyms: ['boldness', 'daring', 'nerve', 'recklessness'],
    antonyms: ['timidity', 'caution', 'meekness'],
  },
  {
    word: 'Banal',
    partOfSpeech: 'adjective',
    meaning: 'Boringly predictable or unoriginal.',
    synonyms: ['trite', 'clichéd', 'unoriginal', 'dull'],
    antonyms: ['original', 'fresh', 'inventive'],
  },
  {
    word: 'Beguile',
    partOfSpeech: 'verb',
    meaning: 'To deceive or charm, often through trickery.',
    synonyms: ['deceive', 'mislead', 'charm', 'delude'],
    antonyms: [],
  },
  {
    word: 'Belligerence',
    partOfSpeech: 'noun',
    meaning: 'Aggressive or hostile behavior.',
    synonyms: ['hostility', 'aggression', 'combativeness'],
    antonyms: ['peacefulness', 'friendliness'],
  },
  {
    word: 'Benefactor',
    partOfSpeech: 'noun',
    meaning: 'A person who gives financial or other assistance.',
    synonyms: ['patron', 'donor', 'sponsor'],
    antonyms: ['beneficiary'],
  },
  {
    word: 'Benevolence',
    partOfSpeech: 'noun',
    meaning: 'An inclination to do good deeds; kindness.',
    synonyms: ['kindness', 'generosity', 'goodwill', 'charity'],
    antonyms: ['malevolence', 'cruelty', 'malice'],
  },
  {
    word: 'Bewildered',
    partOfSpeech: 'adjective',
    meaning: 'Completely confused or puzzled.',
    synonyms: ['confused', 'perplexed', 'baffled', 'puzzled'],
    antonyms: ['clear-headed', 'enlightened'],
  },
  {
    word: 'Bias',
    partOfSpeech: 'noun',
    meaning: 'A prejudice or particular tendency, especially one that prevents fair judgment.',
    synonyms: ['prejudice', 'partiality', 'slant', 'favoritism'],
    antonyms: ['fairness', 'impartiality', 'neutrality'],
  },
  {
    word: 'Bliss',
    partOfSpeech: 'noun',
    meaning: 'Supreme happiness; utter joy.',
    synonyms: ['joy', 'euphoria', 'ecstasy', 'delight'],
    antonyms: ['misery', 'agony', 'despair'],
  },
  {
    word: 'Boisterous',
    partOfSpeech: 'adjective',
    meaning: 'Loud, energetic, and unrestrained.',
    synonyms: ['rowdy', 'rambunctious', 'unruly', 'noisy'],
    antonyms: ['quiet', 'calm', 'subdued'],
  },
  {
    word: 'Bounty',
    partOfSpeech: 'noun',
    meaning: 'Generosity in giving; a reward.',
    synonyms: ['generosity', 'reward', 'largesse'],
    antonyms: ['stinginess'],
  },
  {
    word: 'Bravado',
    partOfSpeech: 'noun',
    meaning: 'A showy, pretentious display of courage.',
    synonyms: ['swagger', 'bluster', 'boastfulness'],
    antonyms: ['timidity', 'humility'],
  },
  {
    word: 'Brevity',
    partOfSpeech: 'noun',
    meaning: 'The quality of being brief; conciseness.',
    synonyms: ['conciseness', 'briefness', 'terseness'],
    antonyms: ['verbosity', 'wordiness'],
  },
  {
    word: 'Cache',
    partOfSpeech: 'noun',
    meaning: 'A hidden store of things, or the hiding place itself.',
    synonyms: ['stash', 'stockpile', 'hoard'],
    antonyms: [],
  },
  {
    word: 'Cajole',
    partOfSpeech: 'verb',
    meaning: 'To persuade someone through flattery or gentle coaxing.',
    synonyms: ['coax', 'wheedle', 'persuade', 'entice'],
    antonyms: [],
  },
  {
    word: 'Candor',
    partOfSpeech: 'noun',
    meaning: 'Frankness and sincerity in speech.',
    synonyms: ['honesty', 'frankness', 'openness', 'sincerity'],
    antonyms: ['deceit', 'secrecy', 'dishonesty'],
  },
  {
    word: 'Caprice',
    partOfSpeech: 'noun',
    meaning: 'A sudden, unpredictable change in behavior or mood.',
    synonyms: ['whim', 'impulse', 'fancy'],
    antonyms: ['consistency', 'steadiness'],
  },
  {
    word: 'Celestial',
    partOfSpeech: 'adjective',
    meaning: 'Relating to the sky or heavens.',
    synonyms: ['heavenly', 'astral', 'cosmic'],
    antonyms: ['earthly', 'terrestrial'],
  },
  {
    word: 'Censor',
    partOfSpeech: 'verb',
    meaning: 'To remove or suppress material considered objectionable.',
    synonyms: ['suppress', 'ban', 'redact', 'edit'],
    antonyms: ['permit', 'allow', 'publish'],
  },
  {
    word: 'Chasm',
    partOfSpeech: 'noun',
    meaning: 'A deep gorge or canyon; a wide gap.',
    synonyms: ['gorge', 'canyon', 'abyss', 'rift'],
    antonyms: [],
  },
  {
    word: 'Chronic',
    partOfSpeech: 'adjective',
    meaning: 'Continuing over a long time; long-standing.',
    synonyms: ['persistent', 'ongoing', 'long-lasting'],
    antonyms: ['temporary', 'acute', 'brief'],
  },
  {
    word: 'Coarse',
    partOfSpeech: 'adjective',
    meaning: 'Rough or loose in texture; crude in speech or manner.',
    synonyms: ['rough', 'crude', 'unrefined'],
    antonyms: ['smooth', 'refined', 'fine'],
  },
  {
    word: 'Collision',
    partOfSpeech: 'noun',
    meaning: 'A crash, clash, or conflict.',
    synonyms: ['crash', 'clash', 'impact'],
    antonyms: [],
  },
  {
    word: 'Compassion',
    partOfSpeech: 'noun',
    meaning: "A deep feeling of pity or sympathy for others' suffering.",
    synonyms: ['sympathy', 'empathy', 'kindness', 'mercy'],
    antonyms: ['indifference', 'callousness', 'cruelty'],
  },
  {
    word: 'Compel',
    partOfSpeech: 'verb',
    meaning: 'To force someone to do something.',
    synonyms: ['force', 'coerce', 'oblige'],
    antonyms: [],
  },
  {
    word: 'Competent',
    partOfSpeech: 'adjective',
    meaning: 'Having sufficient skill or knowledge for a task.',
    synonyms: ['capable', 'proficient', 'skilled', 'qualified'],
    antonyms: ['incompetent', 'inept', 'unskilled'],
  },
  {
    word: 'Concise',
    partOfSpeech: 'adjective',
    meaning: 'Brief and clearly expressed; compact.',
    synonyms: ['succinct', 'terse', 'brief', 'pithy'],
    antonyms: ['verbose', 'wordy', 'long-winded'],
  },
  {
    word: 'Condone',
    partOfSpeech: 'verb',
    meaning: 'To overlook or forgive an offense; to accept as permissible.',
    synonyms: ['excuse', 'forgive', 'overlook', 'permit'],
    antonyms: ['condemn', 'denounce', 'forbid'],
  },
  {
    word: 'Contemplation',
    partOfSpeech: 'noun',
    meaning: 'Deep, thoughtful observation or reflection.',
    synonyms: ['reflection', 'meditation', 'musing'],
    antonyms: [],
  },
  {
    word: 'Contend',
    partOfSpeech: 'verb',
    meaning: 'To struggle or compete; to argue a position.',
    synonyms: ['struggle', 'compete', 'argue', 'dispute'],
    antonyms: [],
  },
  {
    word: 'Convene',
    partOfSpeech: 'verb',
    meaning: 'To come together or call together for a meeting.',
    synonyms: ['assemble', 'gather', 'meet'],
    antonyms: ['adjourn', 'disperse'],
  },
  {
    word: 'Conventional',
    partOfSpeech: 'adjective',
    meaning: 'Based on general agreement or common practice; ordinary.',
    synonyms: ['traditional', 'customary', 'standard', 'ordinary'],
    antonyms: ['unconventional', 'unorthodox', 'original'],
  },
  {
    word: 'Copious',
    partOfSpeech: 'adjective',
    meaning: 'Abundant; large in quantity.',
    synonyms: ['abundant', 'plentiful', 'ample', 'profuse'],
    antonyms: ['scarce', 'meager', 'sparse'],
  },
  {
    word: 'Countenance',
    partOfSpeech: 'noun',
    meaning: "A person's face or facial expression.",
    synonyms: ['face', 'expression', 'appearance'],
    antonyms: [],
  },
  {
    word: 'Courier',
    partOfSpeech: 'noun',
    meaning: 'A person who carries messages or information.',
    synonyms: ['messenger', 'carrier', 'envoy'],
    antonyms: [],
  },
  {
    word: 'Dawdle',
    partOfSpeech: 'verb',
    meaning: 'To waste time by moving or acting slowly.',
    synonyms: ['linger', 'loiter', 'dally', 'procrastinate'],
    antonyms: ['hurry', 'hasten'],
  },
  {
    word: 'Dearth',
    partOfSpeech: 'noun',
    meaning: 'A scarcity or lack of something.',
    synonyms: ['scarcity', 'shortage', 'lack', 'paucity'],
    antonyms: ['abundance', 'surplus', 'plenty'],
  },
  {
    word: 'Debris',
    partOfSpeech: 'noun',
    meaning: 'The scattered remains of something destroyed or discarded.',
    synonyms: ['wreckage', 'rubble', 'remains'],
    antonyms: [],
  },
  {
    word: 'Deceive',
    partOfSpeech: 'verb',
    meaning: 'To mislead or delude someone.',
    synonyms: ['mislead', 'delude', 'trick', 'dupe'],
    antonyms: ['enlighten', 'inform'],
  },
  {
    word: 'Declamation',
    partOfSpeech: 'noun',
    meaning: 'A formal, impassioned speech; an exercise in public speaking.',
    synonyms: ['oration', 'speech', 'rhetoric'],
    antonyms: [],
  },
  {
    word: 'Deficient',
    partOfSpeech: 'adjective',
    meaning: 'Lacking an essential quality or element; inadequate.',
    synonyms: ['inadequate', 'insufficient', 'lacking'],
    antonyms: ['sufficient', 'adequate', 'ample'],
  },
  {
    word: 'Dejected',
    partOfSpeech: 'adjective',
    meaning: 'Sad and depressed; downcast.',
    synonyms: ['downcast', 'despondent', 'sad', 'gloomy'],
    antonyms: ['cheerful', 'elated', 'upbeat'],
  },
  {
    word: 'Delude',
    partOfSpeech: 'verb',
    meaning: "To mislead the mind or judgment of; to deceive.",
    synonyms: ['deceive', 'mislead', 'fool'],
    antonyms: ['enlighten'],
  },
  {
    word: 'Deplore',
    partOfSpeech: 'verb',
    meaning: 'To feel or express strong disapproval of something.',
    synonyms: ['condemn', 'denounce', 'lament'],
    antonyms: ['praise', 'commend', 'approve'],
  },
  {
    word: 'Desolation',
    partOfSpeech: 'noun',
    meaning: 'A state of being deserted, empty, and destroyed.',
    synonyms: ['barrenness', 'devastation', 'emptiness'],
    antonyms: [],
  },
  {
    word: 'Despicable',
    partOfSpeech: 'adjective',
    meaning: 'Deserving of contempt; vile.',
    synonyms: ['contemptible', 'vile', 'detestable'],
    antonyms: ['admirable', 'honorable'],
  },
  {
    word: 'Despondent',
    partOfSpeech: 'adjective',
    meaning: 'In a state of deep depression or hopelessness.',
    synonyms: ['dejected', 'hopeless', 'downhearted'],
    antonyms: ['hopeful', 'optimistic', 'cheerful'],
  },
  {
    word: 'Destitute',
    partOfSpeech: 'adjective',
    meaning: 'Extremely poor; lacking basic necessities.',
    synonyms: ['impoverished', 'poor', 'penniless'],
    antonyms: ['wealthy', 'affluent', 'prosperous'],
  },
  {
    word: 'Devotee',
    partOfSpeech: 'noun',
    meaning: 'A person who is passionately devoted to something.',
    synonyms: ['enthusiast', 'fan', 'follower'],
    antonyms: [],
  },
  {
    word: 'Devout',
    partOfSpeech: 'adjective',
    meaning: 'Deeply religious or sincerely committed.',
    synonyms: ['pious', 'religious', 'faithful'],
    antonyms: ['irreligious', 'indifferent'],
  },
  {
    word: 'Diminish',
    partOfSpeech: 'verb',
    meaning: 'To become or make smaller in size or importance.',
    synonyms: ['decrease', 'reduce', 'lessen', 'shrink'],
    antonyms: ['increase', 'enlarge', 'augment'],
  },
  {
    word: 'Din',
    partOfSpeech: 'noun',
    meaning: 'A loud, confused, and prolonged noise.',
    synonyms: ['racket', 'clamor', 'uproar', 'noise'],
    antonyms: ['silence', 'quiet'],
  },
  {
    word: 'Diplomatic',
    partOfSpeech: 'adjective',
    meaning: 'Tactful and skilled in managing relations between people or nations.',
    synonyms: ['tactful', 'discreet', 'courteous'],
    antonyms: ['tactless', 'undiplomatic', 'blunt'],
  },
  {
    word: 'Disclaim',
    partOfSpeech: 'verb',
    meaning: 'To deny ownership of or responsibility for something.',
    synonyms: ['deny', 'renounce', 'reject'],
    antonyms: ['claim', 'acknowledge'],
  },
  {
    word: 'Discursive',
    partOfSpeech: 'adjective',
    meaning: 'Rambling widely, or digressing from the main topic.',
    synonyms: ['rambling', 'digressive', 'wandering'],
    antonyms: ['concise', 'focused'],
  },
  {
    word: 'Dismal',
    partOfSpeech: 'adjective',
    meaning: 'Causing gloom or depression; cheerless.',
    synonyms: ['gloomy', 'bleak', 'dreary', 'cheerless'],
    antonyms: ['cheerful', 'bright', 'uplifting'],
  },
  {
    word: 'Dispute',
    partOfSpeech: 'noun',
    meaning: 'An argument or disagreement.',
    synonyms: ['argument', 'disagreement', 'quarrel', 'conflict'],
    antonyms: ['agreement', 'accord'],
  },
  {
    word: 'Disseminate',
    partOfSpeech: 'verb',
    meaning: 'To spread or scatter something widely, especially information.',
    synonyms: ['spread', 'distribute', 'circulate', 'broadcast'],
    antonyms: ['withhold', 'suppress'],
  },
  {
    word: 'Divert',
    partOfSpeech: 'verb',
    meaning: 'To change the course of something, or to distract and amuse.',
    synonyms: ['redirect', 'distract', 'deflect'],
    antonyms: [],
  },
  {
    word: 'Dogmatic',
    partOfSpeech: 'adjective',
    meaning: 'Asserting opinions as facts in a forceful, close-minded way.',
    synonyms: ['opinionated', 'rigid', 'inflexible'],
    antonyms: ['open-minded', 'flexible'],
  },
  {
    word: 'Ebullient',
    partOfSpeech: 'adjective',
    meaning: 'Overflowing with enthusiasm or excitement; high-spirited.',
    synonyms: ['exuberant', 'enthusiastic', 'effervescent'],
    antonyms: ['subdued', 'apathetic', 'gloomy'],
  },
  {
    word: 'Eccentric',
    partOfSpeech: 'adjective',
    meaning: 'Deviating from conventional or accepted behavior; odd.',
    synonyms: ['unconventional', 'odd', 'quirky', 'peculiar'],
    antonyms: ['conventional', 'normal', 'ordinary'],
  },
  {
    word: 'Ecstatic',
    partOfSpeech: 'adjective',
    meaning: 'Feeling or expressing overwhelming happiness.',
    synonyms: ['elated', 'overjoyed', 'euphoric', 'thrilled'],
    antonyms: ['miserable', 'despondent'],
  },
  {
    word: 'Elusive',
    partOfSpeech: 'adjective',
    meaning: 'Difficult to find, catch, or achieve.',
    synonyms: ['evasive', 'intangible', 'slippery'],
    antonyms: ['obvious', 'apparent'],
  },
  {
    word: 'Embellish',
    partOfSpeech: 'verb',
    meaning: 'To add decorative details, sometimes to exaggerate.',
    synonyms: ['decorate', 'adorn', 'exaggerate'],
    antonyms: ['simplify'],
  },
  {
    word: 'Eminent',
    partOfSpeech: 'adjective',
    meaning: 'Distinguished and respected within a particular field.',
    synonyms: ['distinguished', 'renowned', 'prominent', 'notable'],
    antonyms: ['obscure', 'unknown', 'insignificant'],
  },
  {
    word: 'Emulate',
    partOfSpeech: 'verb',
    meaning: 'To imitate someone or something admired, in an effort to equal or surpass.',
    synonyms: ['imitate', 'copy', 'mimic'],
    antonyms: [],
  },
  {
    word: 'Encompass',
    partOfSpeech: 'verb',
    meaning: 'To surround or include comprehensively.',
    synonyms: ['surround', 'include', 'encircle', 'contain'],
    antonyms: ['exclude', 'omit'],
  },
  {
    word: 'Endorse',
    partOfSpeech: 'verb',
    meaning: 'To publicly approve of or support something.',
    synonyms: ['approve', 'support', 'sanction', 'back'],
    antonyms: ['oppose', 'reject', 'condemn'],
  },
  {
    word: 'Enigma',
    partOfSpeech: 'noun',
    meaning: 'A person or thing that is mysterious or difficult to understand.',
    synonyms: ['mystery', 'puzzle', 'riddle'],
    antonyms: [],
  },
  {
    word: 'Entice',
    partOfSpeech: 'verb',
    meaning: 'To attract or tempt by offering pleasure or advantage.',
    synonyms: ['tempt', 'lure', 'allure', 'attract'],
    antonyms: ['repel', 'discourage', 'deter'],
  },
  {
    word: 'Era',
    partOfSpeech: 'noun',
    meaning: 'A distinct period of time in history.',
    synonyms: ['period', 'epoch', 'age'],
    antonyms: [],
  },
  {
    word: 'Erudite',
    partOfSpeech: 'adjective',
    meaning: 'Having or showing great knowledge or learning.',
    synonyms: ['learned', 'scholarly', 'knowledgeable'],
    antonyms: ['ignorant', 'uneducated'],
  },
  {
    word: 'Essential',
    partOfSpeech: 'adjective',
    meaning: 'Absolutely necessary; fundamental.',
    synonyms: ['fundamental', 'vital', 'necessary', 'crucial'],
    antonyms: ['unnecessary', 'dispensable', 'optional'],
  },
  {
    word: 'Exhibit',
    partOfSpeech: 'verb',
    meaning: 'To publicly display something for others to see.',
    synonyms: ['display', 'show', 'present', 'showcase'],
    antonyms: ['conceal', 'hide'],
  },
  {
    word: 'Exotic',
    partOfSpeech: 'adjective',
    meaning: 'Originating from a foreign country; strikingly unusual.',
    synonyms: ['foreign', 'unfamiliar', 'unusual'],
    antonyms: ['ordinary', 'familiar', 'native'],
  },
  {
    word: 'Expunge',
    partOfSpeech: 'verb',
    meaning: 'To completely remove or erase something.',
    synonyms: ['erase', 'delete', 'eliminate', 'obliterate'],
    antonyms: ['retain', 'preserve'],
  },
  {
    word: 'Extricate',
    partOfSpeech: 'verb',
    meaning: 'To free someone or something from a difficult situation.',
    synonyms: ['free', 'disentangle', 'release'],
    antonyms: ['entangle', 'trap'],
  },
  {
    word: 'Extroverted',
    partOfSpeech: 'adjective',
    meaning: 'Outgoing and socially confident; interested in others.',
    synonyms: ['outgoing', 'sociable', 'gregarious'],
    antonyms: ['introverted', 'reserved', 'shy'],
  },
  {
    word: 'Fanatic',
    partOfSpeech: 'noun',
    meaning: 'A person with excessive, uncritical enthusiasm, especially in politics or religion.',
    synonyms: ['zealot', 'extremist', 'enthusiast'],
    antonyms: ['moderate', 'skeptic'],
  },
  {
    word: 'Fatal',
    partOfSpeech: 'adjective',
    meaning: 'Causing death or ending in disaster.',
    synonyms: ['deadly', 'lethal', 'mortal'],
    antonyms: ['harmless', 'survivable'],
  },
  {
    word: 'Fatigue',
    partOfSpeech: 'noun',
    meaning: 'Extreme tiredness from mental or physical exertion.',
    synonyms: ['exhaustion', 'weariness', 'tiredness'],
    antonyms: ['energy', 'vigor', 'freshness'],
  },
  {
    word: 'Fauna',
    partOfSpeech: 'noun',
    meaning: 'The animals of a particular region or time period.',
    synonyms: ['wildlife', 'animal life'],
    antonyms: ['flora'],
  },
  {
    word: 'Fervent',
    partOfSpeech: 'adjective',
    meaning: 'Showing great warmth and intensity of feeling.',
    synonyms: ['passionate', 'ardent', 'zealous', 'intense'],
    antonyms: ['indifferent', 'apathetic'],
  },
  {
    word: 'Fidelity',
    partOfSpeech: 'noun',
    meaning: 'Faithfulness to a person, cause, or duty; accuracy.',
    synonyms: ['loyalty', 'faithfulness', 'allegiance'],
    antonyms: ['disloyalty', 'infidelity', 'betrayal'],
  },
  {
    word: 'Flagrant',
    partOfSpeech: 'adjective',
    meaning: 'Conspicuously offensive or obvious; shameless.',
    synonyms: ['blatant', 'glaring', 'obvious', 'outrageous'],
    antonyms: ['subtle', 'inconspicuous'],
  },
  {
    word: 'Flippant',
    partOfSpeech: 'adjective',
    meaning: 'Not showing proper seriousness; casually disrespectful.',
    synonyms: ['glib', 'irreverent', 'cheeky'],
    antonyms: ['serious', 'earnest', 'respectful'],
  },
  {
    word: 'Foretell',
    partOfSpeech: 'verb',
    meaning: 'To predict or indicate something before it happens.',
    synonyms: ['predict', 'forecast', 'prophesy'],
    antonyms: [],
  },
  {
    word: 'Formidable',
    partOfSpeech: 'adjective',
    meaning: 'Inspiring fear, awe, or respect through great strength or size.',
    synonyms: ['daunting', 'intimidating', 'impressive'],
    antonyms: ['unimpressive', 'feeble', 'weak'],
  },
  {
    word: 'Futile',
    partOfSpeech: 'adjective',
    meaning: 'Pointless or ineffective; incapable of producing a result.',
    synonyms: ['pointless', 'useless', 'ineffective', 'vain'],
    antonyms: ['effective', 'worthwhile', 'productive'],
  },
  {
    word: 'Germinate',
    partOfSpeech: 'verb',
    meaning: 'To begin to grow or sprout, as a seed.',
    synonyms: ['sprout', 'bud', 'develop'],
    antonyms: ['decay', 'wither'],
  },
  {
    word: 'Glee',
    partOfSpeech: 'noun',
    meaning: "Great delight or pleasure, especially from one's own good fortune.",
    synonyms: ['joy', 'delight', 'merriment', 'elation'],
    antonyms: ['sorrow', 'misery', 'gloom'],
  },
  {
    word: 'Grovel',
    partOfSpeech: 'verb',
    meaning: 'To act with excessive humility, especially to gain favor; to beg.',
    synonyms: ['beg', 'fawn', 'cower', 'kowtow'],
    antonyms: [],
  },
  {
    word: 'Gruesome',
    partOfSpeech: 'adjective',
    meaning: 'Causing horror or disgust; grisly.',
    synonyms: ['grisly', 'horrific', 'macabre', 'ghastly'],
    antonyms: ['pleasant', 'delightful'],
  },
  {
    word: 'Hallowed',
    partOfSpeech: 'adjective',
    meaning: 'Regarded as holy or sacred.',
    synonyms: ['sacred', 'holy', 'consecrated', 'revered'],
    antonyms: ['desecrated', 'profane'],
  },
  {
    word: 'Harbinger',
    partOfSpeech: 'noun',
    meaning: 'A person or thing that signals the approach of something.',
    synonyms: ['omen', 'forerunner', 'precursor', 'herald'],
    antonyms: [],
  },
  {
    word: 'Hasty',
    partOfSpeech: 'adjective',
    meaning: 'Done with excessive speed; hurried and often careless.',
    synonyms: ['rushed', 'hurried', 'rash', 'impetuous'],
    antonyms: ['careful', 'deliberate', 'unhurried'],
  },
  {
    word: 'Heed',
    partOfSpeech: 'verb',
    meaning: 'To pay close attention to and follow advice or a warning.',
    synonyms: ['obey', 'follow', 'mind', 'observe'],
    antonyms: ['ignore', 'disregard'],
  },
  {
    word: 'Heterogeneous',
    partOfSpeech: 'adjective',
    meaning: 'Made up of parts that are different or diverse in kind.',
    synonyms: ['diverse', 'varied', 'mixed'],
    antonyms: ['homogeneous', 'uniform'],
  },
  {
    word: 'Horrid',
    partOfSpeech: 'adjective',
    meaning: 'Causing horror; extremely unpleasant.',
    synonyms: ['horrible', 'dreadful', 'awful', 'ghastly'],
    antonyms: ['pleasant', 'delightful'],
  },
  {
    word: 'Immaculate',
    partOfSpeech: 'adjective',
    meaning: 'Perfectly clean; free from flaws or mistakes.',
    synonyms: ['spotless', 'flawless', 'pristine'],
    antonyms: ['filthy', 'flawed', 'tainted'],
  },
  {
    word: 'Imminent',
    partOfSpeech: 'adjective',
    meaning: 'About to happen very soon.',
    synonyms: ['impending', 'forthcoming', 'approaching'],
    antonyms: ['distant', 'remote'],
  },
  {
    word: 'Impasse',
    partOfSpeech: 'noun',
    meaning: 'A situation with no way out; a deadlock.',
    synonyms: ['deadlock', 'stalemate', 'standstill'],
    antonyms: ['breakthrough', 'resolution'],
  },
  {
    word: 'Impervious',
    partOfSpeech: 'adjective',
    meaning: 'Not able to be affected, influenced, or penetrated.',
    synonyms: ['impenetrable', 'unaffected', 'immune'],
    antonyms: ['susceptible', 'vulnerable', 'permeable'],
  },
  {
    word: 'Imply',
    partOfSpeech: 'verb',
    meaning: 'To suggest something indirectly, without stating it outright.',
    synonyms: ['suggest', 'hint', 'insinuate'],
    antonyms: ['state', 'declare'],
  },
  {
    word: 'Inadvertent',
    partOfSpeech: 'adjective',
    meaning: 'Not deliberate; happening by accident.',
    synonyms: ['accidental', 'unintentional', 'unplanned'],
    antonyms: ['deliberate', 'intentional'],
  },
  {
    word: 'Incentive',
    partOfSpeech: 'noun',
    meaning: 'Something that motivates or encourages a particular action.',
    synonyms: ['motivation', 'incitement', 'inducement'],
    antonyms: ['deterrent', 'disincentive'],
  },
  {
    word: 'Incredulous',
    partOfSpeech: 'adjective',
    meaning: 'Unwilling or unable to believe something.',
    synonyms: ['skeptical', 'disbelieving', 'doubtful'],
    antonyms: ['credulous', 'trusting'],
  },
  {
    word: 'Inert',
    partOfSpeech: 'adjective',
    meaning: 'Lacking the ability to move or act; sluggish.',
    synonyms: ['motionless', 'inactive', 'sluggish', 'dormant'],
    antonyms: ['active', 'dynamic', 'reactive'],
  },
  {
    word: 'Ingenuity',
    partOfSpeech: 'noun',
    meaning: 'Cleverness or skill in inventing or solving problems.',
    synonyms: ['inventiveness', 'cleverness', 'resourcefulness'],
    antonyms: [],
  },
  {
    word: 'Inhabit',
    partOfSpeech: 'verb',
    meaning: 'To live in or occupy a place.',
    synonyms: ['reside', 'occupy', 'dwell'],
    antonyms: ['vacate', 'abandon'],
  },
  {
    word: 'Innate',
    partOfSpeech: 'adjective',
    meaning: 'Present from birth; natural, not acquired.',
    synonyms: ['inborn', 'natural', 'inherent'],
    antonyms: ['acquired', 'learned'],
  },
  {
    word: 'Insinuation',
    partOfSpeech: 'noun',
    meaning: 'An indirect or sly hint, often suggesting something negative.',
    synonyms: ['hint', 'implication', 'suggestion'],
    antonyms: [],
  },
  {
    word: 'Insomnia',
    partOfSpeech: 'noun',
    meaning: 'The inability to fall or stay asleep.',
    synonyms: ['sleeplessness', 'wakefulness'],
    antonyms: [],
  },
  {
    word: 'Insurgent',
    partOfSpeech: 'noun',
    meaning: 'A person who rises up in revolt against authority.',
    synonyms: ['rebel', 'revolutionary', 'dissident'],
    antonyms: ['loyalist'],
  },
  {
    word: 'Irate',
    partOfSpeech: 'adjective',
    meaning: 'Extremely angry.',
    synonyms: ['furious', 'enraged', 'livid', 'incensed'],
    antonyms: ['calm', 'content', 'pleased'],
  },
  {
    word: 'Jeer',
    partOfSpeech: 'verb',
    meaning: 'To mock or taunt someone rudely.',
    synonyms: ['mock', 'taunt', 'ridicule', 'scoff'],
    antonyms: ['praise', 'cheer', 'applaud'],
  },
  {
    word: 'Jubilant',
    partOfSpeech: 'adjective',
    meaning: 'Feeling or expressing great joy, especially at a success.',
    synonyms: ['elated', 'joyful', 'triumphant', 'overjoyed'],
    antonyms: ['dejected', 'sorrowful'],
  },
  {
    word: 'Judicious',
    partOfSpeech: 'adjective',
    meaning: 'Having or showing sound judgment; sensible.',
    synonyms: ['prudent', 'wise', 'sensible', 'sound'],
    antonyms: ['imprudent', 'reckless', 'injudicious'],
  },
  {
    word: 'Kinetic',
    partOfSpeech: 'adjective',
    meaning: 'Relating to or resulting from motion.',
    synonyms: ['dynamic', 'moving', 'active'],
    antonyms: ['static', 'still'],
  },
  {
    word: 'Lethargy',
    partOfSpeech: 'noun',
    meaning: 'A lack of energy and enthusiasm; sluggishness.',
    synonyms: ['sluggishness', 'drowsiness', 'fatigue', 'apathy'],
    antonyms: ['energy', 'vigor', 'vitality'],
  },
  {
    word: 'Magnanimous',
    partOfSpeech: 'adjective',
    meaning: 'Generous, forgiving, and noble in spirit, especially toward a rival.',
    synonyms: ['generous', 'noble', 'benevolent', 'gracious'],
    antonyms: ['petty', 'mean-spirited', 'vindictive'],
  },
  {
    word: 'Malleable',
    partOfSpeech: 'adjective',
    meaning: 'Able to be shaped, molded, or influenced easily.',
    synonyms: ['pliable', 'adaptable', 'moldable'],
    antonyms: ['rigid', 'inflexible', 'stiff'],
  },
  {
    word: 'Mar',
    partOfSpeech: 'verb',
    meaning: 'To damage or spoil something, making it imperfect.',
    synonyms: ['spoil', 'damage', 'blemish', 'ruin'],
    antonyms: ['enhance', 'improve'],
  },
  {
    word: 'Meager',
    partOfSpeech: 'adjective',
    meaning: 'Very small in amount; insufficient.',
    synonyms: ['scant', 'sparse', 'insufficient', 'paltry'],
    antonyms: ['abundant', 'ample', 'plentiful'],
  },
  {
    word: 'Meek',
    partOfSpeech: 'adjective',
    meaning: 'Quiet, gentle, and submissive by nature.',
    synonyms: ['humble', 'submissive', 'docile', 'timid'],
    antonyms: ['assertive', 'bold', 'confident'],
  },
  {
    word: 'Melancholy',
    partOfSpeech: 'adjective',
    meaning: 'Feeling or expressing deep, thoughtful sadness.',
    synonyms: ['sad', 'gloomy', 'mournful', 'wistful'],
    antonyms: ['cheerful', 'joyful', 'upbeat'],
  },
  {
    word: 'Mimic',
    partOfSpeech: 'verb',
    meaning: "To imitate someone's speech or actions, often for amusement.",
    synonyms: ['imitate', 'copy', 'impersonate'],
    antonyms: [],
  },
  {
    word: 'Mourn',
    partOfSpeech: 'verb',
    meaning: 'To feel or express deep sorrow, especially for a loss.',
    synonyms: ['grieve', 'lament', 'sorrow'],
    antonyms: ['rejoice', 'celebrate'],
  },
  {
    word: 'Nebulous',
    partOfSpeech: 'adjective',
    meaning: 'Vague, unclear, or ill-defined.',
    synonyms: ['vague', 'hazy', 'unclear', 'ambiguous'],
    antonyms: ['clear', 'distinct', 'precise'],
  },
  {
    word: 'Nimble',
    partOfSpeech: 'adjective',
    meaning: 'Quick and light in movement or thought.',
    synonyms: ['agile', 'quick', 'deft', 'dexterous'],
    antonyms: ['clumsy', 'sluggish', 'awkward'],
  },
  {
    word: 'Nomad',
    partOfSpeech: 'noun',
    meaning: 'A person with no permanent home who moves from place to place.',
    synonyms: ['wanderer', 'drifter', 'itinerant'],
    antonyms: ['settler'],
  },
  {
    word: 'Obscure',
    partOfSpeech: 'adjective',
    meaning: 'Not well known; hard to see or understand.',
    synonyms: ['unclear', 'unknown', 'vague', 'hidden'],
    antonyms: ['clear', 'well-known', 'famous'],
  },
  {
    word: 'Obsolete',
    partOfSpeech: 'adjective',
    meaning: 'No longer in use; outdated.',
    synonyms: ['outdated', 'outmoded', 'antiquated'],
    antonyms: ['current', 'modern', 'up-to-date'],
  },
  {
    word: 'Obstinate',
    partOfSpeech: 'adjective',
    meaning: "Stubbornly refusing to change one's mind.",
    synonyms: ['stubborn', 'headstrong', 'inflexible'],
    antonyms: ['flexible', 'compliant', 'yielding'],
  },
  {
    word: 'Obstruct',
    partOfSpeech: 'verb',
    meaning: 'To block or get in the way of something.',
    synonyms: ['block', 'hinder', 'impede', 'hamper'],
    antonyms: ['assist', 'facilitate', 'clear'],
  },
  {
    word: 'Ominous',
    partOfSpeech: 'adjective',
    meaning: 'Giving the impression that something bad is about to happen.',
    synonyms: ['threatening', 'menacing', 'foreboding'],
    antonyms: ['reassuring', 'promising', 'auspicious'],
  },
  {
    word: 'Opportune',
    partOfSpeech: 'adjective',
    meaning: 'Well-suited to a particular purpose; timely.',
    synonyms: ['timely', 'favorable', 'fitting'],
    antonyms: ['inopportune', 'untimely'],
  },
  {
    word: 'Ostentatious',
    partOfSpeech: 'adjective',
    meaning: 'Designed to impress; showy and pretentious.',
    synonyms: ['flashy', 'showy', 'pretentious', 'gaudy'],
    antonyms: ['modest', 'understated', 'restrained'],
  },
  {
    word: 'Palatable',
    partOfSpeech: 'adjective',
    meaning: 'Pleasant tasting, or generally acceptable.',
    synonyms: ['tasty', 'appetizing', 'agreeable'],
    antonyms: ['unpalatable', 'distasteful'],
  },
  {
    word: 'Paradox',
    partOfSpeech: 'noun',
    meaning: 'A statement or situation that seems contradictory but may be true.',
    synonyms: ['contradiction', 'anomaly', 'puzzle'],
    antonyms: [],
  },
  {
    word: 'Passive',
    partOfSpeech: 'adjective',
    meaning: 'Accepting or allowing what happens without resistance; not active.',
    synonyms: ['inactive', 'submissive', 'unresponsive'],
    antonyms: ['active', 'assertive', 'proactive'],
  },
  {
    word: 'Persevere',
    partOfSpeech: 'verb',
    meaning: 'To continue in a course of action despite difficulty.',
    synonyms: ['persist', 'endure', 'continue'],
    antonyms: ['quit', 'give up', 'abandon'],
  },
  {
    word: 'Pious',
    partOfSpeech: 'adjective',
    meaning: 'Devoutly religious or morally virtuous.',
    synonyms: ['devout', 'religious', 'godly'],
    antonyms: ['impious', 'irreverent'],
  },
  {
    word: 'Plausible',
    partOfSpeech: 'adjective',
    meaning: 'Seeming reasonable or probable; believable.',
    synonyms: ['believable', 'credible', 'reasonable'],
    antonyms: ['implausible', 'unbelievable', 'dubious'],
  },
  {
    word: 'Pompous',
    partOfSpeech: 'adjective',
    meaning: 'Self-important and given to excessive formality.',
    synonyms: ['self-important', 'pretentious', 'grandiose'],
    antonyms: ['modest', 'humble', 'unassuming'],
  },
  {
    word: 'Prolific',
    partOfSpeech: 'adjective',
    meaning: 'Producing a great amount or number; highly productive.',
    synonyms: ['productive', 'fruitful', 'abundant'],
    antonyms: ['unproductive', 'barren'],
  },
  {
    word: 'Prophesy',
    partOfSpeech: 'verb',
    meaning: 'To predict the future, especially through divine or special insight.',
    synonyms: ['predict', 'foretell', 'forecast'],
    antonyms: [],
  },
  {
    word: 'Quell',
    partOfSpeech: 'verb',
    meaning: 'To suppress or put an end to something, often forcibly.',
    synonyms: ['suppress', 'crush', 'subdue', 'extinguish'],
    antonyms: ['incite', 'provoke', 'stir up'],
  },
  {
    word: 'Quench',
    partOfSpeech: 'verb',
    meaning: 'To satisfy a thirst or desire; to extinguish.',
    synonyms: ['satisfy', 'slake', 'extinguish'],
    antonyms: ['ignite', 'kindle'],
  },
  {
    word: 'Rancor',
    partOfSpeech: 'noun',
    meaning: 'Bitter, long-lasting resentment or ill will.',
    synonyms: ['bitterness', 'resentment', 'animosity'],
    antonyms: ['goodwill', 'affection'],
  },
  {
    word: 'Ransack',
    partOfSpeech: 'verb',
    meaning: 'To search a place thoroughly and messily, often while stealing.',
    synonyms: ['plunder', 'rummage', 'pillage'],
    antonyms: [],
  },
  {
    word: 'Ravenous',
    partOfSpeech: 'adjective',
    meaning: 'Extremely hungry; eager for something in great quantity.',
    synonyms: ['starving', 'famished', 'voracious'],
    antonyms: ['satisfied', 'full'],
  },
  {
    word: 'Raze',
    partOfSpeech: 'verb',
    meaning: 'To completely destroy or demolish, especially a building.',
    synonyms: ['demolish', 'level', 'flatten', 'destroy'],
    antonyms: ['build', 'construct', 'erect'],
  },
  {
    word: 'Recluse',
    partOfSpeech: 'noun',
    meaning: 'A person who lives in seclusion, avoiding others.',
    synonyms: ['hermit', 'loner', 'isolationist'],
    antonyms: [],
  },
  {
    word: 'Refrain',
    partOfSpeech: 'verb',
    meaning: 'To hold oneself back from doing something.',
    synonyms: ['abstain', 'avoid', 'desist'],
    antonyms: ['indulge', 'proceed'],
  },
  {
    word: 'Regal',
    partOfSpeech: 'adjective',
    meaning: 'Fit for or resembling royalty; splendid.',
    synonyms: ['royal', 'majestic', 'stately', 'noble'],
    antonyms: ['common', 'humble'],
  },
  {
    word: 'Reign',
    partOfSpeech: 'verb',
    meaning: 'To rule as a monarch or hold dominant power.',
    synonyms: ['rule', 'govern', 'dominate'],
    antonyms: ['obey', 'submit'],
  },
  {
    word: 'Reinforce',
    partOfSpeech: 'verb',
    meaning: 'To strengthen something with additional support.',
    synonyms: ['strengthen', 'bolster', 'fortify', 'support'],
    antonyms: ['weaken', 'undermine'],
  },
  {
    word: 'Renowned',
    partOfSpeech: 'adjective',
    meaning: 'Widely known and highly regarded; famous.',
    synonyms: ['famous', 'celebrated', 'illustrious', 'eminent'],
    antonyms: ['obscure', 'unknown', 'unrecognized'],
  },
  {
    word: 'Repugnant',
    partOfSpeech: 'adjective',
    meaning: 'Extremely distasteful or offensive.',
    synonyms: ['repulsive', 'revolting', 'distasteful', 'offensive'],
    antonyms: ['appealing', 'pleasant', 'attractive'],
  },
  {
    word: 'Revel',
    partOfSpeech: 'verb',
    meaning: 'To take great pleasure in something; to celebrate boisterously.',
    synonyms: ['celebrate', 'delight', 'carouse'],
    antonyms: ['mourn', 'lament'],
  },
  {
    word: 'Scarce',
    partOfSpeech: 'adjective',
    meaning: 'Insufficient in supply; rare.',
    synonyms: ['rare', 'sparse', 'limited', 'scant'],
    antonyms: ['abundant', 'plentiful', 'ample'],
  },
  {
    word: 'Scrupulous',
    partOfSpeech: 'adjective',
    meaning: 'Careful and thorough, especially in matters of right and wrong.',
    synonyms: ['meticulous', 'conscientious', 'principled'],
    antonyms: ['unscrupulous', 'careless', 'negligent'],
  },
  {
    word: 'Seethe',
    partOfSpeech: 'verb',
    meaning: 'To be filled with great anger or agitation, as if boiling.',
    synonyms: ['fume', 'boil', 'simmer', 'rage'],
    antonyms: ['calm down', 'relax'],
  },
  {
    word: 'Shrewd',
    partOfSpeech: 'adjective',
    meaning: 'Having sharp judgment; clever in practical matters.',
    synonyms: ['astute', 'cunning', 'sharp', 'perceptive'],
    antonyms: ['naive', 'gullible', 'foolish'],
  },
  {
    word: 'Sinister',
    partOfSpeech: 'adjective',
    meaning: 'Giving the impression that something evil or harmful is happening.',
    synonyms: ['menacing', 'ominous', 'threatening', 'evil'],
    antonyms: ['benign', 'harmless', 'innocent'],
  },
  {
    word: 'Squander',
    partOfSpeech: 'verb',
    meaning: 'To waste money, time, or resources carelessly.',
    synonyms: ['waste', 'misspend', 'fritter away'],
    antonyms: ['conserve', 'save', 'invest'],
  },
  {
    word: 'Staunch',
    partOfSpeech: 'adjective',
    meaning: 'Loyal and steadfast, especially in support of a cause.',
    synonyms: ['loyal', 'steadfast', 'faithful', 'devoted'],
    antonyms: ['disloyal', 'fickle', 'faithless'],
  },
  {
    word: 'Stealthy',
    partOfSpeech: 'adjective',
    meaning: 'Cautious and quiet in order to avoid being noticed.',
    synonyms: ['sneaky', 'furtive', 'covert', 'secretive'],
    antonyms: ['open', 'obvious', 'conspicuous'],
  },
  {
    word: 'Suave',
    partOfSpeech: 'adjective',
    meaning: 'Smooth, confident, and polished in manner, sometimes insincerely.',
    synonyms: ['charming', 'polished', 'debonair', 'smooth-talking'],
    antonyms: ['awkward', 'uncouth', 'gauche'],
  },
  {
    word: 'Subdue',
    partOfSpeech: 'verb',
    meaning: 'To bring under control, or to reduce in intensity.',
    synonyms: ['conquer', 'overpower', 'quell', 'tame'],
    antonyms: ['incite', 'unleash'],
  },
  {
    word: 'Succumb',
    partOfSpeech: 'verb',
    meaning: 'To give in to something overwhelming; to yield.',
    synonyms: ['yield', 'surrender', 'capitulate', 'submit'],
    antonyms: ['resist', 'withstand', 'overcome'],
  },
  {
    word: 'Suffice',
    partOfSpeech: 'verb',
    meaning: 'To be enough or adequate.',
    synonyms: ['satisfy', 'serve', 'meet'],
    antonyms: [],
  },
  {
    word: 'Suppress',
    partOfSpeech: 'verb',
    meaning: 'To forcibly hold back or put an end to.',
    synonyms: ['restrain', 'repress', 'crush', 'stifle'],
    antonyms: ['release', 'unleash', 'encourage'],
  },
  {
    word: 'Surmise',
    partOfSpeech: 'verb',
    meaning: 'To guess or infer something without certain evidence.',
    synonyms: ['guess', 'infer', 'conjecture', 'speculate'],
    antonyms: ['know', 'confirm'],
  },
  {
    word: 'Synopsis',
    partOfSpeech: 'noun',
    meaning: 'A brief summary or outline.',
    synonyms: ['summary', 'outline', 'overview'],
    antonyms: [],
  },
  {
    word: 'Taciturn',
    partOfSpeech: 'adjective',
    meaning: 'Reserved and reluctant to speak much.',
    synonyms: ['reticent', 'quiet', 'reserved', 'uncommunicative'],
    antonyms: ['talkative', 'loquacious', 'garrulous'],
  },
  {
    word: 'Tactful',
    partOfSpeech: 'adjective',
    meaning: "Considerate and skillful in dealing with others' feelings.",
    synonyms: ['diplomatic', 'considerate', 'sensitive'],
    antonyms: ['tactless', 'blunt', 'insensitive'],
  },
  {
    word: 'Tangible',
    partOfSpeech: 'adjective',
    meaning: 'Able to be touched or physically felt; real and definite.',
    synonyms: ['palpable', 'concrete', 'physical', 'real'],
    antonyms: ['intangible', 'abstract'],
  },
  {
    word: 'Terminate',
    partOfSpeech: 'verb',
    meaning: 'To bring to an end.',
    synonyms: ['end', 'conclude', 'stop', 'cease'],
    antonyms: ['begin', 'start', 'initiate'],
  },
  {
    word: 'Terse',
    partOfSpeech: 'adjective',
    meaning: 'Brief and to the point, sometimes to the point of curtness.',
    synonyms: ['concise', 'curt', 'brief', 'succinct'],
    antonyms: ['wordy', 'verbose', 'rambling'],
  },
  {
    word: 'Trepidation',
    partOfSpeech: 'noun',
    meaning: 'A feeling of fear or anxiety about something that may happen.',
    synonyms: ['apprehension', 'anxiety', 'dread', 'unease'],
    antonyms: ['confidence', 'calm', 'composure'],
  },
  {
    word: 'Trite',
    partOfSpeech: 'adjective',
    meaning: 'Overused and lacking originality.',
    synonyms: ['clichéd', 'banal', 'hackneyed', 'stale'],
    antonyms: ['original', 'fresh', 'novel'],
  },
  {
    word: 'Tyranny',
    partOfSpeech: 'noun',
    meaning: 'Cruel and oppressive rule or use of power.',
    synonyms: ['oppression', 'despotism', 'autocracy'],
    antonyms: ['democracy', 'freedom', 'liberty'],
  },
  {
    word: 'Ultimate',
    partOfSpeech: 'adjective',
    meaning: 'Being the final or most extreme point; beyond which nothing further exists.',
    synonyms: ['final', 'supreme', 'utmost', 'conclusive'],
    antonyms: ['initial', 'preliminary'],
  },
  {
    word: 'Unanimous',
    partOfSpeech: 'adjective',
    meaning: 'Fully agreed on by everyone involved.',
    synonyms: ['united', 'agreed', 'unopposed'],
    antonyms: ['divided', 'contested'],
  },
  {
    word: 'Vacuous',
    partOfSpeech: 'adjective',
    meaning: 'Lacking substance or seriousness; empty-headed.',
    synonyms: ['empty', 'vapid', 'mindless', 'inane'],
    antonyms: ['thoughtful', 'profound', 'substantive'],
  },
  {
    word: 'Vague',
    partOfSpeech: 'adjective',
    meaning: 'Not clearly expressed or understood; uncertain.',
    synonyms: ['unclear', 'ambiguous', 'hazy', 'imprecise'],
    antonyms: ['clear', 'precise', 'definite'],
  },
  {
    word: 'Vehement',
    partOfSpeech: 'adjective',
    meaning: 'Showing strong, forceful feeling.',
    synonyms: ['forceful', 'intense', 'passionate', 'fierce'],
    antonyms: ['mild', 'calm', 'indifferent'],
  },
  {
    word: 'Vex',
    partOfSpeech: 'verb',
    meaning: 'To annoy or irritate greatly.',
    synonyms: ['irritate', 'annoy', 'provoke', 'exasperate'],
    antonyms: ['soothe', 'please', 'calm'],
  },
  {
    word: 'Vivacious',
    partOfSpeech: 'adjective',
    meaning: 'Lively and full of energetic spirit.',
    synonyms: ['lively', 'animated', 'spirited', 'energetic'],
    antonyms: ['dull', 'listless', 'lethargic'],
  },
  {
    word: 'Wantonly',
    partOfSpeech: 'adverb',
    meaning: 'In a deliberately unprovoked or unjustified manner; without cause.',
    synonyms: ['recklessly', 'gratuitously', 'needlessly'],
    antonyms: [],
  },
  {
    word: 'Wrath',
    partOfSpeech: 'noun',
    meaning: 'Extreme or intense anger.',
    synonyms: ['fury', 'rage', 'ire', 'anger'],
    antonyms: ['calm', 'serenity', 'forgiveness'],
  },
  {
    word: 'Wretched',
    partOfSpeech: 'adjective',
    meaning: 'Extremely unhappy or unfortunate; miserable.',
    synonyms: ['miserable', 'pitiful', 'forlorn', 'distressed'],
    antonyms: ['content', 'fortunate', 'joyful'],
  },
  {
    word: 'Zealous',
    partOfSpeech: 'adjective',
    meaning: 'Showing great energy or enthusiasm in pursuit of a cause.',
    synonyms: ['enthusiastic', 'fervent', 'ardent', 'passionate'],
    antonyms: ['apathetic', 'indifferent', 'half-hearted'],
  },
];
